use iced::{Font, font::Family};

use iced::widget::{Text, text};

pub enum FontAwesomeBrands {
    AccessibleIcon,
    Accusoft,
    Adn,
    Adversal,
    Affiliatetheme,
    Airbnb,
    Algolia,
    Alipay,
    Amazon,
    AmazonPay,
    Amilia,
    Android,
    Angellist,
    Angrycreative,
    Angular,
    AppStore,
    AppStoreIos,
    Apper,
    Apple,
    ApplePay,
    Artstation,
    Asymmetrik,
    Atlassian,
    Audible,
    Autoprefixer,
    Avianex,
    Aviato,
    Aws,
    Bandcamp,
    BattleNet,
    Behance,
    Bilibili,
    Bimobject,
    Bitbucket,
    Bitcoin,
    Bity,
    BlackTie,
    Blackberry,
    Blogger,
    BloggerB,
    Bluesky,
    Bluetooth,
    BluetoothB,
    Bootstrap,
    Bots,
    Brave,
    BraveReverse,
    Btc,
    Buffer,
    Buromobelexperte,
    BuyNLarge,
    Buysellads,
    CanadianMapleLeaf,
    CcAmazonPay,
    CcAmex,
    CcApplePay,
    CcDinersClub,
    CcDiscover,
    CcJcb,
    CcMastercard,
    CcPaypal,
    CcStripe,
    CcVisa,
    Centercode,
    Centos,
    Chrome,
    Chromecast,
    Cloudflare,
    Cloudscale,
    Cloudsmith,
    Cloudversify,
    Cmplid,
    Codepen,
    Codiepie,
    Confluence,
    Connectdevelop,
    Contao,
    CottonBureau,
    Cpanel,
    CreativeCommons,
    CreativeCommonsBy,
    CreativeCommonsNc,
    CreativeCommonsNcEu,
    CreativeCommonsNcJp,
    CreativeCommonsNd,
    CreativeCommonsPd,
    CreativeCommonsPdAlt,
    CreativeCommonsRemix,
    CreativeCommonsSa,
    CreativeCommonsSampling,
    CreativeCommonsSamplingPlus,
    CreativeCommonsShare,
    CreativeCommonsZero,
    CriticalRole,
    Css,
    Css3,
    Css3Alt,
    Cuttlefish,
    DAndD,
    DAndDBeyond,
    Dailymotion,
    DartLang,
    Dashcube,
    Debian,
    Deezer,
    Delicious,
    Deploydog,
    Deskpro,
    Dev,
    Deviantart,
    Dhl,
    Diaspora,
    Digg,
    DigitalOcean,
    Discord,
    Discourse,
    Dochub,
    Docker,
    Draft2digital,
    Dribbble,
    Dropbox,
    Drupal,
    Dyalog,
    Earlybirds,
    Ebay,
    Edge,
    EdgeLegacy,
    Elementor,
    Ello,
    Ember,
    Empire,
    Envira,
    Erlang,
    Ethereum,
    Etsy,
    Evernote,
    Expeditedssl,
    Facebook,
    FacebookF,
    FacebookMessenger,
    FantasyFlightGames,
    Fedex,
    Fedora,
    Figma,
    FilesPinwheel,
    Firefox,
    FirefoxBrowser,
    FirstOrder,
    FirstOrderAlt,
    Firstdraft,
    Flickr,
    Flipboard,
    Flutter,
    Fly,
    FontAwesome,
    Fonticons,
    FonticonsFi,
    FortAwesome,
    FortAwesomeAlt,
    Forumbee,
    Foursquare,
    FreeCodeCamp,
    Freebsd,
    Fulcrum,
    GalacticRepublic,
    GalacticSenate,
    GetPocket,
    Gg,
    GgCircle,
    Git,
    GitAlt,
    Github,
    GithubAlt,
    Gitkraken,
    Gitlab,
    Gitter,
    Glide,
    GlideG,
    Gofore,
    Golang,
    Goodreads,
    GoodreadsG,
    Google,
    GoogleDrive,
    GooglePay,
    GooglePlay,
    GooglePlus,
    GooglePlusG,
    GoogleScholar,
    GoogleWallet,
    Gratipay,
    Grav,
    Gripfire,
    Grunt,
    Guilded,
    Gulp,
    HackerNews,
    Hackerrank,
    Hashnode,
    Hips,
    HireAHelper,
    Hive,
    Hooli,
    Hornbill,
    Hotjar,
    Houzz,
    Html5,
    Hubspot,
    Ideal,
    Imdb,
    Instagram,
    Instalod,
    Intercom,
    InternetExplorer,
    Invision,
    Ioxhost,
    ItchIo,
    Itunes,
    ItunesNote,
    Java,
    JediOrder,
    Jenkins,
    Jira,
    Joget,
    Joomla,
    Js,
    Jsfiddle,
    Jxl,
    Kaggle,
    Keybase,
    Keycdn,
    Kickstarter,
    KickstarterK,
    Korvue,
    Laravel,
    Lastfm,
    Leanpub,
    Less,
    Letterboxd,
    Line,
    Linkedin,
    LinkedinIn,
    Linode,
    Linux,
    Lyft,
    Magento,
    Mailchimp,
    Mandalorian,
    Markdown,
    Mastodon,
    Maxcdn,
    Mdb,
    Medapps,
    Medium,
    Medrt,
    Meetup,
    Megaport,
    Mendeley,
    Meta,
    Microblog,
    Microsoft,
    Mintbit,
    Mix,
    Mixcloud,
    Mixer,
    Mizuni,
    Modx,
    Monero,
    Napster,
    Neos,
    NfcDirectional,
    NfcSymbol,
    Nimblr,
    Node,
    NodeJs,
    Npm,
    Ns8,
    Nutritionix,
    OctopusDeploy,
    Odnoklassniki,
    Odysee,
    OldRepublic,
    Opencart,
    Openid,
    Opensuse,
    Opera,
    OptinMonster,
    Orcid,
    Osi,
    Padlet,
    Page4,
    Pagelines,
    Palfed,
    Patreon,
    Paypal,
    Perbyte,
    Periscope,
    Phabricator,
    PhoenixFramework,
    PhoenixSquadron,
    Php,
    PiedPiper,
    PiedPiperAlt,
    PiedPiperHat,
    PiedPiperPp,
    Pinterest,
    PinterestP,
    Pix,
    Pixiv,
    Playstation,
    ProductHunt,
    Pushed,
    Python,
    Qq,
    Quinscape,
    Quora,
    RProject,
    RaspberryPi,
    Ravelry,
    React,
    Reacteurope,
    Readme,
    Rebel,
    RedRiver,
    Reddit,
    RedditAlien,
    Redhat,
    Renren,
    Replyd,
    Researchgate,
    Resolving,
    Rev,
    Rocketchat,
    Rockrms,
    Rust,
    Safari,
    Salesforce,
    Sass,
    Schlix,
    Screenpal,
    Scribd,
    Searchengin,
    Sellcast,
    Sellsy,
    Servicestack,
    Shirtsinbulk,
    Shoelace,
    Shopify,
    Shopware,
    SignalMessenger,
    Simplybuilt,
    Sistrix,
    Sith,
    Sitrox,
    Sketch,
    Skyatlas,
    Skype,
    Slack,
    Slideshare,
    Snapchat,
    Soundcloud,
    Sourcetree,
    SpaceAwesome,
    Speakap,
    SpeakerDeck,
    Spotify,
    SquareBehance,
    SquareBluesky,
    SquareDribbble,
    SquareFacebook,
    SquareFontAwesome,
    SquareFontAwesomeStroke,
    SquareGit,
    SquareGithub,
    SquareGitlab,
    SquareGooglePlus,
    SquareHackerNews,
    SquareInstagram,
    SquareJs,
    SquareLastfm,
    SquareLetterboxd,
    SquareOdnoklassniki,
    SquarePiedPiper,
    SquarePinterest,
    SquareReddit,
    SquareSnapchat,
    SquareSteam,
    SquareThreads,
    SquareTumblr,
    SquareTwitter,
    SquareUpwork,
    SquareViadeo,
    SquareVimeo,
    SquareWebAwesome,
    SquareWebAwesomeStroke,
    SquareWhatsapp,
    SquareXTwitter,
    SquareXing,
    SquareYoutube,
    Squarespace,
    StackExchange,
    StackOverflow,
    Stackpath,
    Staylinked,
    Steam,
    SteamSymbol,
    StickerMule,
    Strava,
    Stripe,
    StripeS,
    Stubber,
    Studiovinari,
    Stumbleupon,
    StumbleuponCircle,
    Superpowers,
    Supple,
    Suse,
    Swift,
    Symfony,
    Teamspeak,
    Telegram,
    TencentWeibo,
    TheRedYeti,
    Themeco,
    Themeisle,
    ThinkPeaks,
    Threads,
    Tiktok,
    TradeFederation,
    Trello,
    Tumblr,
    Twitch,
    Twitter,
    Typo3,
    Uber,
    Ubuntu,
    Uikit,
    Umbraco,
    Uncharted,
    Uniregistry,
    Unity,
    Unsplash,
    Untappd,
    Ups,
    Upwork,
    Usb,
    Usps,
    Ussunnah,
    Vaadin,
    Viacoin,
    Viadeo,
    Viber,
    Vimeo,
    VimeoV,
    Vine,
    Vk,
    Vnv,
    Vuejs,
    WatchmanMonitoring,
    Waze,
    WebAwesome,
    Webflow,
    Weebly,
    Weibo,
    Weixin,
    Whatsapp,
    Whmcs,
    WikipediaW,
    Windows,
    Wirsindhandwerk,
    Wix,
    WizardsOfTheCoast,
    Wodu,
    WolfPackBattalion,
    Wordpress,
    WordpressSimple,
    Wpbeginner,
    Wpexplorer,
    Wpforms,
    Wpressr,
    XTwitter,
    Xbox,
    Xing,
    YCombinator,
    Yahoo,
    Yammer,
    Yandex,
    YandexInternational,
    Yarn,
    Yelp,
    Yoast,
    Youtube,
    Zhihu,
}

impl FontAwesomeBrands {
    pub fn to_string(&self) -> String {
        match self {
            Self::AccessibleIcon => "\u{f368}".to_owned(),
            Self::Accusoft => "\u{f369}".to_owned(),
            Self::Adn => "\u{f170}".to_owned(),
            Self::Adversal => "\u{f36a}".to_owned(),
            Self::Affiliatetheme => "\u{f36b}".to_owned(),
            Self::Airbnb => "\u{f834}".to_owned(),
            Self::Algolia => "\u{f36c}".to_owned(),
            Self::Alipay => "\u{f642}".to_owned(),
            Self::Amazon => "\u{f270}".to_owned(),
            Self::AmazonPay => "\u{f42c}".to_owned(),
            Self::Amilia => "\u{f36d}".to_owned(),
            Self::Android => "\u{f17b}".to_owned(),
            Self::Angellist => "\u{f209}".to_owned(),
            Self::Angrycreative => "\u{f36e}".to_owned(),
            Self::Angular => "\u{f420}".to_owned(),
            Self::AppStore => "\u{f36f}".to_owned(),
            Self::AppStoreIos => "\u{f370}".to_owned(),
            Self::Apper => "\u{f371}".to_owned(),
            Self::Apple => "\u{f179}".to_owned(),
            Self::ApplePay => "\u{f415}".to_owned(),
            Self::Artstation => "\u{f77a}".to_owned(),
            Self::Asymmetrik => "\u{f372}".to_owned(),
            Self::Atlassian => "\u{f77b}".to_owned(),
            Self::Audible => "\u{f373}".to_owned(),
            Self::Autoprefixer => "\u{f41c}".to_owned(),
            Self::Avianex => "\u{f374}".to_owned(),
            Self::Aviato => "\u{f421}".to_owned(),
            Self::Aws => "\u{f375}".to_owned(),
            Self::Bandcamp => "\u{f2d5}".to_owned(),
            Self::BattleNet => "\u{f835}".to_owned(),
            Self::Behance => "\u{f1b4}".to_owned(),
            Self::Bilibili => "\u{e3d9}".to_owned(),
            Self::Bimobject => "\u{f378}".to_owned(),
            Self::Bitbucket => "\u{f171}".to_owned(),
            Self::Bitcoin => "\u{f379}".to_owned(),
            Self::Bity => "\u{f37a}".to_owned(),
            Self::BlackTie => "\u{f27e}".to_owned(),
            Self::Blackberry => "\u{f37b}".to_owned(),
            Self::Blogger => "\u{f37c}".to_owned(),
            Self::BloggerB => "\u{f37d}".to_owned(),
            Self::Bluesky => "\u{e671}".to_owned(),
            Self::Bluetooth => "\u{f293}".to_owned(),
            Self::BluetoothB => "\u{f294}".to_owned(),
            Self::Bootstrap => "\u{f836}".to_owned(),
            Self::Bots => "\u{e340}".to_owned(),
            Self::Brave => "\u{e63c}".to_owned(),
            Self::BraveReverse => "\u{e63d}".to_owned(),
            Self::Btc => "\u{f15a}".to_owned(),
            Self::Buffer => "\u{f837}".to_owned(),
            Self::Buromobelexperte => "\u{f37f}".to_owned(),
            Self::BuyNLarge => "\u{f8a6}".to_owned(),
            Self::Buysellads => "\u{f20d}".to_owned(),
            Self::CanadianMapleLeaf => "\u{f785}".to_owned(),
            Self::CcAmazonPay => "\u{f42d}".to_owned(),
            Self::CcAmex => "\u{f1f3}".to_owned(),
            Self::CcApplePay => "\u{f416}".to_owned(),
            Self::CcDinersClub => "\u{f24c}".to_owned(),
            Self::CcDiscover => "\u{f1f2}".to_owned(),
            Self::CcJcb => "\u{f24b}".to_owned(),
            Self::CcMastercard => "\u{f1f1}".to_owned(),
            Self::CcPaypal => "\u{f1f4}".to_owned(),
            Self::CcStripe => "\u{f1f5}".to_owned(),
            Self::CcVisa => "\u{f1f0}".to_owned(),
            Self::Centercode => "\u{f380}".to_owned(),
            Self::Centos => "\u{f789}".to_owned(),
            Self::Chrome => "\u{f268}".to_owned(),
            Self::Chromecast => "\u{f838}".to_owned(),
            Self::Cloudflare => "\u{e07d}".to_owned(),
            Self::Cloudscale => "\u{f383}".to_owned(),
            Self::Cloudsmith => "\u{f384}".to_owned(),
            Self::Cloudversify => "\u{f385}".to_owned(),
            Self::Cmplid => "\u{e360}".to_owned(),
            Self::Codepen => "\u{f1cb}".to_owned(),
            Self::Codiepie => "\u{f284}".to_owned(),
            Self::Confluence => "\u{f78d}".to_owned(),
            Self::Connectdevelop => "\u{f20e}".to_owned(),
            Self::Contao => "\u{f26d}".to_owned(),
            Self::CottonBureau => "\u{f89e}".to_owned(),
            Self::Cpanel => "\u{f388}".to_owned(),
            Self::CreativeCommons => "\u{f25e}".to_owned(),
            Self::CreativeCommonsBy => "\u{f4e7}".to_owned(),
            Self::CreativeCommonsNc => "\u{f4e8}".to_owned(),
            Self::CreativeCommonsNcEu => "\u{f4e9}".to_owned(),
            Self::CreativeCommonsNcJp => "\u{f4ea}".to_owned(),
            Self::CreativeCommonsNd => "\u{f4eb}".to_owned(),
            Self::CreativeCommonsPd => "\u{f4ec}".to_owned(),
            Self::CreativeCommonsPdAlt => "\u{f4ed}".to_owned(),
            Self::CreativeCommonsRemix => "\u{f4ee}".to_owned(),
            Self::CreativeCommonsSa => "\u{f4ef}".to_owned(),
            Self::CreativeCommonsSampling => "\u{f4f0}".to_owned(),
            Self::CreativeCommonsSamplingPlus => "\u{f4f1}".to_owned(),
            Self::CreativeCommonsShare => "\u{f4f2}".to_owned(),
            Self::CreativeCommonsZero => "\u{f4f3}".to_owned(),
            Self::CriticalRole => "\u{f6c9}".to_owned(),
            Self::Css => "\u{e6a2}".to_owned(),
            Self::Css3 => "\u{f13c}".to_owned(),
            Self::Css3Alt => "\u{f38b}".to_owned(),
            Self::Cuttlefish => "\u{f38c}".to_owned(),
            Self::DAndD => "\u{f38d}".to_owned(),
            Self::DAndDBeyond => "\u{f6ca}".to_owned(),
            Self::Dailymotion => "\u{e052}".to_owned(),
            Self::DartLang => "\u{e693}".to_owned(),
            Self::Dashcube => "\u{f210}".to_owned(),
            Self::Debian => "\u{e60b}".to_owned(),
            Self::Deezer => "\u{e077}".to_owned(),
            Self::Delicious => "\u{f1a5}".to_owned(),
            Self::Deploydog => "\u{f38e}".to_owned(),
            Self::Deskpro => "\u{f38f}".to_owned(),
            Self::Dev => "\u{f6cc}".to_owned(),
            Self::Deviantart => "\u{f1bd}".to_owned(),
            Self::Dhl => "\u{f790}".to_owned(),
            Self::Diaspora => "\u{f791}".to_owned(),
            Self::Digg => "\u{f1a6}".to_owned(),
            Self::DigitalOcean => "\u{f391}".to_owned(),
            Self::Discord => "\u{f392}".to_owned(),
            Self::Discourse => "\u{f393}".to_owned(),
            Self::Dochub => "\u{f394}".to_owned(),
            Self::Docker => "\u{f395}".to_owned(),
            Self::Draft2digital => "\u{f396}".to_owned(),
            Self::Dribbble => "\u{f17d}".to_owned(),
            Self::Dropbox => "\u{f16b}".to_owned(),
            Self::Drupal => "\u{f1a9}".to_owned(),
            Self::Dyalog => "\u{f399}".to_owned(),
            Self::Earlybirds => "\u{f39a}".to_owned(),
            Self::Ebay => "\u{f4f4}".to_owned(),
            Self::Edge => "\u{f282}".to_owned(),
            Self::EdgeLegacy => "\u{e078}".to_owned(),
            Self::Elementor => "\u{f430}".to_owned(),
            Self::Ello => "\u{f5f1}".to_owned(),
            Self::Ember => "\u{f423}".to_owned(),
            Self::Empire => "\u{f1d1}".to_owned(),
            Self::Envira => "\u{f299}".to_owned(),
            Self::Erlang => "\u{f39d}".to_owned(),
            Self::Ethereum => "\u{f42e}".to_owned(),
            Self::Etsy => "\u{f2d7}".to_owned(),
            Self::Evernote => "\u{f839}".to_owned(),
            Self::Expeditedssl => "\u{f23e}".to_owned(),
            Self::Facebook => "\u{f09a}".to_owned(),
            Self::FacebookF => "\u{f39e}".to_owned(),
            Self::FacebookMessenger => "\u{f39f}".to_owned(),
            Self::FantasyFlightGames => "\u{f6dc}".to_owned(),
            Self::Fedex => "\u{f797}".to_owned(),
            Self::Fedora => "\u{f798}".to_owned(),
            Self::Figma => "\u{f799}".to_owned(),
            Self::FilesPinwheel => "\u{e69f}".to_owned(),
            Self::Firefox => "\u{f269}".to_owned(),
            Self::FirefoxBrowser => "\u{e007}".to_owned(),
            Self::FirstOrder => "\u{f2b0}".to_owned(),
            Self::FirstOrderAlt => "\u{f50a}".to_owned(),
            Self::Firstdraft => "\u{f3a1}".to_owned(),
            Self::Flickr => "\u{f16e}".to_owned(),
            Self::Flipboard => "\u{f44d}".to_owned(),
            Self::Flutter => "\u{e694}".to_owned(),
            Self::Fly => "\u{f417}".to_owned(),
            Self::FontAwesome => "\u{f2b4}".to_owned(),
            Self::Fonticons => "\u{f280}".to_owned(),
            Self::FonticonsFi => "\u{f3a2}".to_owned(),
            Self::FortAwesome => "\u{f286}".to_owned(),
            Self::FortAwesomeAlt => "\u{f3a3}".to_owned(),
            Self::Forumbee => "\u{f211}".to_owned(),
            Self::Foursquare => "\u{f180}".to_owned(),
            Self::FreeCodeCamp => "\u{f2c5}".to_owned(),
            Self::Freebsd => "\u{f3a4}".to_owned(),
            Self::Fulcrum => "\u{f50b}".to_owned(),
            Self::GalacticRepublic => "\u{f50c}".to_owned(),
            Self::GalacticSenate => "\u{f50d}".to_owned(),
            Self::GetPocket => "\u{f265}".to_owned(),
            Self::Gg => "\u{f260}".to_owned(),
            Self::GgCircle => "\u{f261}".to_owned(),
            Self::Git => "\u{f1d3}".to_owned(),
            Self::GitAlt => "\u{f841}".to_owned(),
            Self::Github => "\u{f09b}".to_owned(),
            Self::GithubAlt => "\u{f113}".to_owned(),
            Self::Gitkraken => "\u{f3a6}".to_owned(),
            Self::Gitlab => "\u{f296}".to_owned(),
            Self::Gitter => "\u{f426}".to_owned(),
            Self::Glide => "\u{f2a5}".to_owned(),
            Self::GlideG => "\u{f2a6}".to_owned(),
            Self::Gofore => "\u{f3a7}".to_owned(),
            Self::Golang => "\u{e40f}".to_owned(),
            Self::Goodreads => "\u{f3a8}".to_owned(),
            Self::GoodreadsG => "\u{f3a9}".to_owned(),
            Self::Google => "\u{f1a0}".to_owned(),
            Self::GoogleDrive => "\u{f3aa}".to_owned(),
            Self::GooglePay => "\u{e079}".to_owned(),
            Self::GooglePlay => "\u{f3ab}".to_owned(),
            Self::GooglePlus => "\u{f2b3}".to_owned(),
            Self::GooglePlusG => "\u{f0d5}".to_owned(),
            Self::GoogleScholar => "\u{e63b}".to_owned(),
            Self::GoogleWallet => "\u{f1ee}".to_owned(),
            Self::Gratipay => "\u{f184}".to_owned(),
            Self::Grav => "\u{f2d6}".to_owned(),
            Self::Gripfire => "\u{f3ac}".to_owned(),
            Self::Grunt => "\u{f3ad}".to_owned(),
            Self::Guilded => "\u{e07e}".to_owned(),
            Self::Gulp => "\u{f3ae}".to_owned(),
            Self::HackerNews => "\u{f1d4}".to_owned(),
            Self::Hackerrank => "\u{f5f7}".to_owned(),
            Self::Hashnode => "\u{e499}".to_owned(),
            Self::Hips => "\u{f452}".to_owned(),
            Self::HireAHelper => "\u{f3b0}".to_owned(),
            Self::Hive => "\u{e07f}".to_owned(),
            Self::Hooli => "\u{f427}".to_owned(),
            Self::Hornbill => "\u{f592}".to_owned(),
            Self::Hotjar => "\u{f3b1}".to_owned(),
            Self::Houzz => "\u{f27c}".to_owned(),
            Self::Html5 => "\u{f13b}".to_owned(),
            Self::Hubspot => "\u{f3b2}".to_owned(),
            Self::Ideal => "\u{e013}".to_owned(),
            Self::Imdb => "\u{f2d8}".to_owned(),
            Self::Instagram => "\u{f16d}".to_owned(),
            Self::Instalod => "\u{e081}".to_owned(),
            Self::Intercom => "\u{f7af}".to_owned(),
            Self::InternetExplorer => "\u{f26b}".to_owned(),
            Self::Invision => "\u{f7b0}".to_owned(),
            Self::Ioxhost => "\u{f208}".to_owned(),
            Self::ItchIo => "\u{f83a}".to_owned(),
            Self::Itunes => "\u{f3b4}".to_owned(),
            Self::ItunesNote => "\u{f3b5}".to_owned(),
            Self::Java => "\u{f4e4}".to_owned(),
            Self::JediOrder => "\u{f50e}".to_owned(),
            Self::Jenkins => "\u{f3b6}".to_owned(),
            Self::Jira => "\u{f7b1}".to_owned(),
            Self::Joget => "\u{f3b7}".to_owned(),
            Self::Joomla => "\u{f1aa}".to_owned(),
            Self::Js => "\u{f3b8}".to_owned(),
            Self::Jsfiddle => "\u{f1cc}".to_owned(),
            Self::Jxl => "\u{e67b}".to_owned(),
            Self::Kaggle => "\u{f5fa}".to_owned(),
            Self::Keybase => "\u{f4f5}".to_owned(),
            Self::Keycdn => "\u{f3ba}".to_owned(),
            Self::Kickstarter => "\u{f3bb}".to_owned(),
            Self::KickstarterK => "\u{f3bc}".to_owned(),
            Self::Korvue => "\u{f42f}".to_owned(),
            Self::Laravel => "\u{f3bd}".to_owned(),
            Self::Lastfm => "\u{f202}".to_owned(),
            Self::Leanpub => "\u{f212}".to_owned(),
            Self::Less => "\u{f41d}".to_owned(),
            Self::Letterboxd => "\u{e62d}".to_owned(),
            Self::Line => "\u{f3c0}".to_owned(),
            Self::Linkedin => "\u{f08c}".to_owned(),
            Self::LinkedinIn => "\u{f0e1}".to_owned(),
            Self::Linode => "\u{f2b8}".to_owned(),
            Self::Linux => "\u{f17c}".to_owned(),
            Self::Lyft => "\u{f3c3}".to_owned(),
            Self::Magento => "\u{f3c4}".to_owned(),
            Self::Mailchimp => "\u{f59e}".to_owned(),
            Self::Mandalorian => "\u{f50f}".to_owned(),
            Self::Markdown => "\u{f60f}".to_owned(),
            Self::Mastodon => "\u{f4f6}".to_owned(),
            Self::Maxcdn => "\u{f136}".to_owned(),
            Self::Mdb => "\u{f8ca}".to_owned(),
            Self::Medapps => "\u{f3c6}".to_owned(),
            Self::Medium => "\u{f23a}".to_owned(),
            Self::Medrt => "\u{f3c8}".to_owned(),
            Self::Meetup => "\u{f2e0}".to_owned(),
            Self::Megaport => "\u{f5a3}".to_owned(),
            Self::Mendeley => "\u{f7b3}".to_owned(),
            Self::Meta => "\u{e49b}".to_owned(),
            Self::Microblog => "\u{e01a}".to_owned(),
            Self::Microsoft => "\u{f3ca}".to_owned(),
            Self::Mintbit => "\u{e62f}".to_owned(),
            Self::Mix => "\u{f3cb}".to_owned(),
            Self::Mixcloud => "\u{f289}".to_owned(),
            Self::Mixer => "\u{e056}".to_owned(),
            Self::Mizuni => "\u{f3cc}".to_owned(),
            Self::Modx => "\u{f285}".to_owned(),
            Self::Monero => "\u{f3d0}".to_owned(),
            Self::Napster => "\u{f3d2}".to_owned(),
            Self::Neos => "\u{f612}".to_owned(),
            Self::NfcDirectional => "\u{e530}".to_owned(),
            Self::NfcSymbol => "\u{e531}".to_owned(),
            Self::Nimblr => "\u{f5a8}".to_owned(),
            Self::Node => "\u{f419}".to_owned(),
            Self::NodeJs => "\u{f3d3}".to_owned(),
            Self::Npm => "\u{f3d4}".to_owned(),
            Self::Ns8 => "\u{f3d5}".to_owned(),
            Self::Nutritionix => "\u{f3d6}".to_owned(),
            Self::OctopusDeploy => "\u{e082}".to_owned(),
            Self::Odnoklassniki => "\u{f263}".to_owned(),
            Self::Odysee => "\u{e5c6}".to_owned(),
            Self::OldRepublic => "\u{f510}".to_owned(),
            Self::Opencart => "\u{f23d}".to_owned(),
            Self::Openid => "\u{f19b}".to_owned(),
            Self::Opensuse => "\u{e62b}".to_owned(),
            Self::Opera => "\u{f26a}".to_owned(),
            Self::OptinMonster => "\u{f23c}".to_owned(),
            Self::Orcid => "\u{f8d2}".to_owned(),
            Self::Osi => "\u{f41a}".to_owned(),
            Self::Padlet => "\u{e4a0}".to_owned(),
            Self::Page4 => "\u{f3d7}".to_owned(),
            Self::Pagelines => "\u{f18c}".to_owned(),
            Self::Palfed => "\u{f3d8}".to_owned(),
            Self::Patreon => "\u{f3d9}".to_owned(),
            Self::Paypal => "\u{f1ed}".to_owned(),
            Self::Perbyte => "\u{e083}".to_owned(),
            Self::Periscope => "\u{f3da}".to_owned(),
            Self::Phabricator => "\u{f3db}".to_owned(),
            Self::PhoenixFramework => "\u{f3dc}".to_owned(),
            Self::PhoenixSquadron => "\u{f511}".to_owned(),
            Self::Php => "\u{f457}".to_owned(),
            Self::PiedPiper => "\u{f2ae}".to_owned(),
            Self::PiedPiperAlt => "\u{f1a8}".to_owned(),
            Self::PiedPiperHat => "\u{f4e5}".to_owned(),
            Self::PiedPiperPp => "\u{f1a7}".to_owned(),
            Self::Pinterest => "\u{f0d2}".to_owned(),
            Self::PinterestP => "\u{f231}".to_owned(),
            Self::Pix => "\u{e43a}".to_owned(),
            Self::Pixiv => "\u{e640}".to_owned(),
            Self::Playstation => "\u{f3df}".to_owned(),
            Self::ProductHunt => "\u{f288}".to_owned(),
            Self::Pushed => "\u{f3e1}".to_owned(),
            Self::Python => "\u{f3e2}".to_owned(),
            Self::Qq => "\u{f1d6}".to_owned(),
            Self::Quinscape => "\u{f459}".to_owned(),
            Self::Quora => "\u{f2c4}".to_owned(),
            Self::RProject => "\u{f4f7}".to_owned(),
            Self::RaspberryPi => "\u{f7bb}".to_owned(),
            Self::Ravelry => "\u{f2d9}".to_owned(),
            Self::React => "\u{f41b}".to_owned(),
            Self::Reacteurope => "\u{f75d}".to_owned(),
            Self::Readme => "\u{f4d5}".to_owned(),
            Self::Rebel => "\u{f1d0}".to_owned(),
            Self::RedRiver => "\u{f3e3}".to_owned(),
            Self::Reddit => "\u{f1a1}".to_owned(),
            Self::RedditAlien => "\u{f281}".to_owned(),
            Self::Redhat => "\u{f7bc}".to_owned(),
            Self::Renren => "\u{f18b}".to_owned(),
            Self::Replyd => "\u{f3e6}".to_owned(),
            Self::Researchgate => "\u{f4f8}".to_owned(),
            Self::Resolving => "\u{f3e7}".to_owned(),
            Self::Rev => "\u{f5b2}".to_owned(),
            Self::Rocketchat => "\u{f3e8}".to_owned(),
            Self::Rockrms => "\u{f3e9}".to_owned(),
            Self::Rust => "\u{e07a}".to_owned(),
            Self::Safari => "\u{f267}".to_owned(),
            Self::Salesforce => "\u{f83b}".to_owned(),
            Self::Sass => "\u{f41e}".to_owned(),
            Self::Schlix => "\u{f3ea}".to_owned(),
            Self::Screenpal => "\u{e570}".to_owned(),
            Self::Scribd => "\u{f28a}".to_owned(),
            Self::Searchengin => "\u{f3eb}".to_owned(),
            Self::Sellcast => "\u{f2da}".to_owned(),
            Self::Sellsy => "\u{f213}".to_owned(),
            Self::Servicestack => "\u{f3ec}".to_owned(),
            Self::Shirtsinbulk => "\u{f214}".to_owned(),
            Self::Shoelace => "\u{e60c}".to_owned(),
            Self::Shopify => "\u{e057}".to_owned(),
            Self::Shopware => "\u{f5b5}".to_owned(),
            Self::SignalMessenger => "\u{e663}".to_owned(),
            Self::Simplybuilt => "\u{f215}".to_owned(),
            Self::Sistrix => "\u{f3ee}".to_owned(),
            Self::Sith => "\u{f512}".to_owned(),
            Self::Sitrox => "\u{e44a}".to_owned(),
            Self::Sketch => "\u{f7c6}".to_owned(),
            Self::Skyatlas => "\u{f216}".to_owned(),
            Self::Skype => "\u{f17e}".to_owned(),
            Self::Slack => "\u{f198}".to_owned(),
            Self::Slideshare => "\u{f1e7}".to_owned(),
            Self::Snapchat => "\u{f2ab}".to_owned(),
            Self::Soundcloud => "\u{f1be}".to_owned(),
            Self::Sourcetree => "\u{f7d3}".to_owned(),
            Self::SpaceAwesome => "\u{e5ac}".to_owned(),
            Self::Speakap => "\u{f3f3}".to_owned(),
            Self::SpeakerDeck => "\u{f83c}".to_owned(),
            Self::Spotify => "\u{f1bc}".to_owned(),
            Self::SquareBehance => "\u{f1b5}".to_owned(),
            Self::SquareBluesky => "\u{e6a3}".to_owned(),
            Self::SquareDribbble => "\u{f397}".to_owned(),
            Self::SquareFacebook => "\u{f082}".to_owned(),
            Self::SquareFontAwesome => "\u{e5ad}".to_owned(),
            Self::SquareFontAwesomeStroke => "\u{f35c}".to_owned(),
            Self::SquareGit => "\u{f1d2}".to_owned(),
            Self::SquareGithub => "\u{f092}".to_owned(),
            Self::SquareGitlab => "\u{e5ae}".to_owned(),
            Self::SquareGooglePlus => "\u{f0d4}".to_owned(),
            Self::SquareHackerNews => "\u{f3af}".to_owned(),
            Self::SquareInstagram => "\u{e055}".to_owned(),
            Self::SquareJs => "\u{f3b9}".to_owned(),
            Self::SquareLastfm => "\u{f203}".to_owned(),
            Self::SquareLetterboxd => "\u{e62e}".to_owned(),
            Self::SquareOdnoklassniki => "\u{f264}".to_owned(),
            Self::SquarePiedPiper => "\u{e01e}".to_owned(),
            Self::SquarePinterest => "\u{f0d3}".to_owned(),
            Self::SquareReddit => "\u{f1a2}".to_owned(),
            Self::SquareSnapchat => "\u{f2ad}".to_owned(),
            Self::SquareSteam => "\u{f1b7}".to_owned(),
            Self::SquareThreads => "\u{e619}".to_owned(),
            Self::SquareTumblr => "\u{f174}".to_owned(),
            Self::SquareTwitter => "\u{f081}".to_owned(),
            Self::SquareUpwork => "\u{e67c}".to_owned(),
            Self::SquareViadeo => "\u{f2aa}".to_owned(),
            Self::SquareVimeo => "\u{f194}".to_owned(),
            Self::SquareWebAwesome => "\u{e683}".to_owned(),
            Self::SquareWebAwesomeStroke => "\u{e684}".to_owned(),
            Self::SquareWhatsapp => "\u{f40c}".to_owned(),
            Self::SquareXTwitter => "\u{e61a}".to_owned(),
            Self::SquareXing => "\u{f169}".to_owned(),
            Self::SquareYoutube => "\u{f431}".to_owned(),
            Self::Squarespace => "\u{f5be}".to_owned(),
            Self::StackExchange => "\u{f18d}".to_owned(),
            Self::StackOverflow => "\u{f16c}".to_owned(),
            Self::Stackpath => "\u{f842}".to_owned(),
            Self::Staylinked => "\u{f3f5}".to_owned(),
            Self::Steam => "\u{f1b6}".to_owned(),
            Self::SteamSymbol => "\u{f3f6}".to_owned(),
            Self::StickerMule => "\u{f3f7}".to_owned(),
            Self::Strava => "\u{f428}".to_owned(),
            Self::Stripe => "\u{f429}".to_owned(),
            Self::StripeS => "\u{f42a}".to_owned(),
            Self::Stubber => "\u{e5c7}".to_owned(),
            Self::Studiovinari => "\u{f3f8}".to_owned(),
            Self::Stumbleupon => "\u{f1a4}".to_owned(),
            Self::StumbleuponCircle => "\u{f1a3}".to_owned(),
            Self::Superpowers => "\u{f2dd}".to_owned(),
            Self::Supple => "\u{f3f9}".to_owned(),
            Self::Suse => "\u{f7d6}".to_owned(),
            Self::Swift => "\u{f8e1}".to_owned(),
            Self::Symfony => "\u{f83d}".to_owned(),
            Self::Teamspeak => "\u{f4f9}".to_owned(),
            Self::Telegram => "\u{f2c6}".to_owned(),
            Self::TencentWeibo => "\u{f1d5}".to_owned(),
            Self::TheRedYeti => "\u{f69d}".to_owned(),
            Self::Themeco => "\u{f5c6}".to_owned(),
            Self::Themeisle => "\u{f2b2}".to_owned(),
            Self::ThinkPeaks => "\u{f731}".to_owned(),
            Self::Threads => "\u{e618}".to_owned(),
            Self::Tiktok => "\u{e07b}".to_owned(),
            Self::TradeFederation => "\u{f513}".to_owned(),
            Self::Trello => "\u{f181}".to_owned(),
            Self::Tumblr => "\u{f173}".to_owned(),
            Self::Twitch => "\u{f1e8}".to_owned(),
            Self::Twitter => "\u{f099}".to_owned(),
            Self::Typo3 => "\u{f42b}".to_owned(),
            Self::Uber => "\u{f402}".to_owned(),
            Self::Ubuntu => "\u{f7df}".to_owned(),
            Self::Uikit => "\u{f403}".to_owned(),
            Self::Umbraco => "\u{f8e8}".to_owned(),
            Self::Uncharted => "\u{e084}".to_owned(),
            Self::Uniregistry => "\u{f404}".to_owned(),
            Self::Unity => "\u{e049}".to_owned(),
            Self::Unsplash => "\u{e07c}".to_owned(),
            Self::Untappd => "\u{f405}".to_owned(),
            Self::Ups => "\u{f7e0}".to_owned(),
            Self::Upwork => "\u{e641}".to_owned(),
            Self::Usb => "\u{f287}".to_owned(),
            Self::Usps => "\u{f7e1}".to_owned(),
            Self::Ussunnah => "\u{f407}".to_owned(),
            Self::Vaadin => "\u{f408}".to_owned(),
            Self::Viacoin => "\u{f237}".to_owned(),
            Self::Viadeo => "\u{f2a9}".to_owned(),
            Self::Viber => "\u{f409}".to_owned(),
            Self::Vimeo => "\u{f40a}".to_owned(),
            Self::VimeoV => "\u{f27d}".to_owned(),
            Self::Vine => "\u{f1ca}".to_owned(),
            Self::Vk => "\u{f189}".to_owned(),
            Self::Vnv => "\u{f40b}".to_owned(),
            Self::Vuejs => "\u{f41f}".to_owned(),
            Self::WatchmanMonitoring => "\u{e087}".to_owned(),
            Self::Waze => "\u{f83f}".to_owned(),
            Self::WebAwesome => "\u{e682}".to_owned(),
            Self::Webflow => "\u{e65c}".to_owned(),
            Self::Weebly => "\u{f5cc}".to_owned(),
            Self::Weibo => "\u{f18a}".to_owned(),
            Self::Weixin => "\u{f1d7}".to_owned(),
            Self::Whatsapp => "\u{f232}".to_owned(),
            Self::Whmcs => "\u{f40d}".to_owned(),
            Self::WikipediaW => "\u{f266}".to_owned(),
            Self::Windows => "\u{f17a}".to_owned(),
            Self::Wirsindhandwerk => "\u{e2d0}".to_owned(),
            Self::Wix => "\u{f5cf}".to_owned(),
            Self::WizardsOfTheCoast => "\u{f730}".to_owned(),
            Self::Wodu => "\u{e088}".to_owned(),
            Self::WolfPackBattalion => "\u{f514}".to_owned(),
            Self::Wordpress => "\u{f19a}".to_owned(),
            Self::WordpressSimple => "\u{f411}".to_owned(),
            Self::Wpbeginner => "\u{f297}".to_owned(),
            Self::Wpexplorer => "\u{f2de}".to_owned(),
            Self::Wpforms => "\u{f298}".to_owned(),
            Self::Wpressr => "\u{f3e4}".to_owned(),
            Self::XTwitter => "\u{e61b}".to_owned(),
            Self::Xbox => "\u{f412}".to_owned(),
            Self::Xing => "\u{f168}".to_owned(),
            Self::YCombinator => "\u{f23b}".to_owned(),
            Self::Yahoo => "\u{f19e}".to_owned(),
            Self::Yammer => "\u{f840}".to_owned(),
            Self::Yandex => "\u{f413}".to_owned(),
            Self::YandexInternational => "\u{f414}".to_owned(),
            Self::Yarn => "\u{f7e3}".to_owned(),
            Self::Yelp => "\u{f1e9}".to_owned(),
            Self::Yoast => "\u{f2b1}".to_owned(),
            Self::Youtube => "\u{f167}".to_owned(),
            Self::Zhihu => "\u{f63f}".to_owned(),
        }
    }
}

pub fn brands<'a>(c: FontAwesomeBrands) -> Text<'a> {
    text(c.to_string()).font(FONTAWESOMEBRANDS_FONT)
}

const FONTAWESOMEBRANDS_FONT: Font = Font {
    family: Family::Name("Font Awesome 6 Brands"),
    weight: iced::font::Weight::Normal,
    ..Font::DEFAULT
};
