use iced::{Font, font::Family};

use iced::widget::{Text, text};

pub enum FontAwesomeBrands {
    AccessibleIcon,
    Accusoft,
    Adn,
    Adversal,
    Affiliatetheme,
    Airbnb,
    Algolia,
    Alipay,
    Amazon,
    AmazonPay,
    Amilia,
    Android,
    Angellist,
    Angrycreative,
    Angular,
    AppStore,
    AppStoreIos,
    Apper,
    Apple,
    ApplePay,
    Artstation,
    Asymmetrik,
    Atlassian,
    Audible,
    Autoprefixer,
    Avianex,
    Aviato,
    Aws,
    Bandcamp,
    BattleNet,
    Behance,
    Bilibili,
    Bimobject,
    Bitbucket,
    Bitcoin,
    Bity,
    BlackTie,
    Blackberry,
    Blogger,
    BloggerB,
    Bluesky,
    Bluetooth,
    BluetoothB,
    Bootstrap,
    Bots,
    Brave,
    BraveReverse,
    Btc,
    Buffer,
    Buromobelexperte,
    BuyNLarge,
    Buysellads,
    CanadianMapleLeaf,
    CcAmazonPay,
    CcAmex,
    CcApplePay,
    CcDinersClub,
    CcDiscover,
    CcJcb,
    CcMastercard,
    CcPaypal,
    CcStripe,
    CcVisa,
    Centercode,
    Centos,
    Chrome,
    Chromecast,
    Cloudflare,
    Cloudscale,
    Cloudsmith,
    Cloudversify,
    Cmplid,
    Codepen,
    Codiepie,
    Confluence,
    Connectdevelop,
    Contao,
    CottonBureau,
    Cpanel,
    CreativeCommons,
    CreativeCommonsBy,
    CreativeCommonsNc,
    CreativeCommonsNcEu,
    CreativeCommonsNcJp,
    CreativeCommonsNd,
    CreativeCommonsPd,
    CreativeCommonsPdAlt,
    CreativeCommonsRemix,
    CreativeCommonsSa,
    CreativeCommonsSampling,
    CreativeCommonsSamplingPlus,
    CreativeCommonsShare,
    CreativeCommonsZero,
    CriticalRole,
    Css,
    Css3,
    Css3Alt,
    Cuttlefish,
    DAndD,
    DAndDBeyond,
    Dailymotion,
    DartLang,
    Dashcube,
    Debian,
    Deezer,
    Delicious,
    Deploydog,
    Deskpro,
    Dev,
    Deviantart,
    Dhl,
    Diaspora,
    Digg,
    DigitalOcean,
    Discord,
    Discourse,
    Dochub,
    Docker,
    Draft2digital,
    Dribbble,
    Dropbox,
    Drupal,
    Dyalog,
    Earlybirds,
    Ebay,
    Edge,
    EdgeLegacy,
    Elementor,
    Ello,
    Ember,
    Empire,
    Envira,
    Erlang,
    Ethereum,
    Etsy,
    Evernote,
    Expeditedssl,
    Facebook,
    FacebookF,
    FacebookMessenger,
    FantasyFlightGames,
    Fedex,
    Fedora,
    Figma,
    FilesPinwheel,
    Firefox,
    FirefoxBrowser,
    FirstOrder,
    FirstOrderAlt,
    Firstdraft,
    Flickr,
    Flipboard,
    Flutter,
    Fly,
    FontAwesome,
    Fonticons,
    FonticonsFi,
    FortAwesome,
    FortAwesomeAlt,
    Forumbee,
    Foursquare,
    FreeCodeCamp,
    Freebsd,
    Fulcrum,
    GalacticRepublic,
    GalacticSenate,
    GetPocket,
    Gg,
    GgCircle,
    Git,
    GitAlt,
    Github,
    GithubAlt,
    Gitkraken,
    Gitlab,
    Gitter,
    Glide,
    GlideG,
    Gofore,
    Golang,
    Goodreads,
    GoodreadsG,
    Google,
    GoogleDrive,
    GooglePay,
    GooglePlay,
    GooglePlus,
    GooglePlusG,
    GoogleScholar,
    GoogleWallet,
    Gratipay,
    Grav,
    Gripfire,
    Grunt,
    Guilded,
    Gulp,
    HackerNews,
    Hackerrank,
    Hashnode,
    Hips,
    HireAHelper,
    Hive,
    Hooli,
    Hornbill,
    Hotjar,
    Houzz,
    Html5,
    Hubspot,
    Ideal,
    Imdb,
    Instagram,
    Instalod,
    Intercom,
    InternetExplorer,
    Invision,
    Ioxhost,
    ItchIo,
    Itunes,
    ItunesNote,
    Java,
    JediOrder,
    Jenkins,
    Jira,
    Joget,
    Joomla,
    Js,
    Jsfiddle,
    Jxl,
    Kaggle,
    Keybase,
    Keycdn,
    Kickstarter,
    KickstarterK,
    Korvue,
    Laravel,
    Lastfm,
    Leanpub,
    Less,
    Letterboxd,
    Line,
    Linkedin,
    LinkedinIn,
    Linode,
    Linux,
    Lyft,
    Magento,
    Mailchimp,
    Mandalorian,
    Markdown,
    Mastodon,
    Maxcdn,
    Mdb,
    Medapps,
    Medium,
    Medrt,
    Meetup,
    Megaport,
    Mendeley,
    Meta,
    Microblog,
    Microsoft,
    Mintbit,
    Mix,
    Mixcloud,
    Mixer,
    Mizuni,
    Modx,
    Monero,
    Napster,
    Neos,
    NfcDirectional,
    NfcSymbol,
    Nimblr,
    Node,
    NodeJs,
    Npm,
    Ns8,
    Nutritionix,
    OctopusDeploy,
    Odnoklassniki,
    Odysee,
    OldRepublic,
    Opencart,
    Openid,
    Opensuse,
    Opera,
    OptinMonster,
    Orcid,
    Osi,
    Padlet,
    Page4,
    Pagelines,
    Palfed,
    Patreon,
    Paypal,
    Perbyte,
    Periscope,
    Phabricator,
    PhoenixFramework,
    PhoenixSquadron,
    Php,
    PiedPiper,
    PiedPiperAlt,
    PiedPiperHat,
    PiedPiperPp,
    Pinterest,
    PinterestP,
    Pix,
    Pixiv,
    Playstation,
    ProductHunt,
    Pushed,
    Python,
    Qq,
    Quinscape,
    Quora,
    RProject,
    RaspberryPi,
    Ravelry,
    React,
    Reacteurope,
    Readme,
    Rebel,
    RedRiver,
    Reddit,
    RedditAlien,
    Redhat,
    Renren,
    Replyd,
    Researchgate,
    Resolving,
    Rev,
    Rocketchat,
    Rockrms,
    Rust,
    Safari,
    Salesforce,
    Sass,
    Schlix,
    Screenpal,
    Scribd,
    Searchengin,
    Sellcast,
    Sellsy,
    Servicestack,
    Shirtsinbulk,
    Shoelace,
    Shopify,
    Shopware,
    SignalMessenger,
    Simplybuilt,
    Sistrix,
    Sith,
    Sitrox,
    Sketch,
    Skyatlas,
    Skype,
    Slack,
    Slideshare,
    Snapchat,
    Soundcloud,
    Sourcetree,
    SpaceAwesome,
    Speakap,
    SpeakerDeck,
    Spotify,
    SquareBehance,
    SquareBluesky,
    SquareDribbble,
    SquareFacebook,
    SquareFontAwesome,
    SquareFontAwesomeStroke,
    SquareGit,
    SquareGithub,
    SquareGitlab,
    SquareGooglePlus,
    SquareHackerNews,
    SquareInstagram,
    SquareJs,
    SquareLastfm,
    SquareLetterboxd,
    SquareOdnoklassniki,
    SquarePiedPiper,
    SquarePinterest,
    SquareReddit,
    SquareSnapchat,
    SquareSteam,
    SquareThreads,
    SquareTumblr,
    SquareTwitter,
    SquareUpwork,
    SquareViadeo,
    SquareVimeo,
    SquareWebAwesome,
    SquareWebAwesomeStroke,
    SquareWhatsapp,
    SquareXTwitter,
    SquareXing,
    SquareYoutube,
    Squarespace,
    StackExchange,
    StackOverflow,
    Stackpath,
    Staylinked,
    Steam,
    SteamSymbol,
    StickerMule,
    Strava,
    Stripe,
    StripeS,
    Stubber,
    Studiovinari,
    Stumbleupon,
    StumbleuponCircle,
    Superpowers,
    Supple,
    Suse,
    Swift,
    Symfony,
    Teamspeak,
    Telegram,
    TencentWeibo,
    TheRedYeti,
    Themeco,
    Themeisle,
    ThinkPeaks,
    Threads,
    Tiktok,
    TradeFederation,
    Trello,
    Tumblr,
    Twitch,
    Twitter,
    Typo3,
    Uber,
    Ubuntu,
    Uikit,
    Umbraco,
    Uncharted,
    Uniregistry,
    Unity,
    Unsplash,
    Untappd,
    Ups,
    Upwork,
    Usb,
    Usps,
    Ussunnah,
    Vaadin,
    Viacoin,
    Viadeo,
    Viber,
    Vimeo,
    VimeoV,
    Vine,
    Vk,
    Vnv,
    Vuejs,
    WatchmanMonitoring,
    Waze,
    WebAwesome,
    Webflow,
    Weebly,
    Weibo,
    Weixin,
    Whatsapp,
    Whmcs,
    WikipediaW,
    Windows,
    Wirsindhandwerk,
    Wix,
    WizardsOfTheCoast,
    Wodu,
    WolfPackBattalion,
    Wordpress,
    WordpressSimple,
    Wpbeginner,
    Wpexplorer,
    Wpforms,
    Wpressr,
    XTwitter,
    Xbox,
    Xing,
    YCombinator,
    Yahoo,
    Yammer,
    Yandex,
    YandexInternational,
    Yarn,
    Yelp,
    Yoast,
    Youtube,
    Zhihu,
}

impl FontAwesomeBrands {
    pub fn to_string(&self) -> &str {
        match self {
            Self::AccessibleIcon => "\u{f368}",
            Self::Accusoft => "\u{f369}",
            Self::Adn => "\u{f170}",
            Self::Adversal => "\u{f36a}",
            Self::Affiliatetheme => "\u{f36b}",
            Self::Airbnb => "\u{f834}",
            Self::Algolia => "\u{f36c}",
            Self::Alipay => "\u{f642}",
            Self::Amazon => "\u{f270}",
            Self::AmazonPay => "\u{f42c}",
            Self::Amilia => "\u{f36d}",
            Self::Android => "\u{f17b}",
            Self::Angellist => "\u{f209}",
            Self::Angrycreative => "\u{f36e}",
            Self::Angular => "\u{f420}",
            Self::AppStore => "\u{f36f}",
            Self::AppStoreIos => "\u{f370}",
            Self::Apper => "\u{f371}",
            Self::Apple => "\u{f179}",
            Self::ApplePay => "\u{f415}",
            Self::Artstation => "\u{f77a}",
            Self::Asymmetrik => "\u{f372}",
            Self::Atlassian => "\u{f77b}",
            Self::Audible => "\u{f373}",
            Self::Autoprefixer => "\u{f41c}",
            Self::Avianex => "\u{f374}",
            Self::Aviato => "\u{f421}",
            Self::Aws => "\u{f375}",
            Self::Bandcamp => "\u{f2d5}",
            Self::BattleNet => "\u{f835}",
            Self::Behance => "\u{f1b4}",
            Self::Bilibili => "\u{e3d9}",
            Self::Bimobject => "\u{f378}",
            Self::Bitbucket => "\u{f171}",
            Self::Bitcoin => "\u{f379}",
            Self::Bity => "\u{f37a}",
            Self::BlackTie => "\u{f27e}",
            Self::Blackberry => "\u{f37b}",
            Self::Blogger => "\u{f37c}",
            Self::BloggerB => "\u{f37d}",
            Self::Bluesky => "\u{e671}",
            Self::Bluetooth => "\u{f293}",
            Self::BluetoothB => "\u{f294}",
            Self::Bootstrap => "\u{f836}",
            Self::Bots => "\u{e340}",
            Self::Brave => "\u{e63c}",
            Self::BraveReverse => "\u{e63d}",
            Self::Btc => "\u{f15a}",
            Self::Buffer => "\u{f837}",
            Self::Buromobelexperte => "\u{f37f}",
            Self::BuyNLarge => "\u{f8a6}",
            Self::Buysellads => "\u{f20d}",
            Self::CanadianMapleLeaf => "\u{f785}",
            Self::CcAmazonPay => "\u{f42d}",
            Self::CcAmex => "\u{f1f3}",
            Self::CcApplePay => "\u{f416}",
            Self::CcDinersClub => "\u{f24c}",
            Self::CcDiscover => "\u{f1f2}",
            Self::CcJcb => "\u{f24b}",
            Self::CcMastercard => "\u{f1f1}",
            Self::CcPaypal => "\u{f1f4}",
            Self::CcStripe => "\u{f1f5}",
            Self::CcVisa => "\u{f1f0}",
            Self::Centercode => "\u{f380}",
            Self::Centos => "\u{f789}",
            Self::Chrome => "\u{f268}",
            Self::Chromecast => "\u{f838}",
            Self::Cloudflare => "\u{e07d}",
            Self::Cloudscale => "\u{f383}",
            Self::Cloudsmith => "\u{f384}",
            Self::Cloudversify => "\u{f385}",
            Self::Cmplid => "\u{e360}",
            Self::Codepen => "\u{f1cb}",
            Self::Codiepie => "\u{f284}",
            Self::Confluence => "\u{f78d}",
            Self::Connectdevelop => "\u{f20e}",
            Self::Contao => "\u{f26d}",
            Self::CottonBureau => "\u{f89e}",
            Self::Cpanel => "\u{f388}",
            Self::CreativeCommons => "\u{f25e}",
            Self::CreativeCommonsBy => "\u{f4e7}",
            Self::CreativeCommonsNc => "\u{f4e8}",
            Self::CreativeCommonsNcEu => "\u{f4e9}",
            Self::CreativeCommonsNcJp => "\u{f4ea}",
            Self::CreativeCommonsNd => "\u{f4eb}",
            Self::CreativeCommonsPd => "\u{f4ec}",
            Self::CreativeCommonsPdAlt => "\u{f4ed}",
            Self::CreativeCommonsRemix => "\u{f4ee}",
            Self::CreativeCommonsSa => "\u{f4ef}",
            Self::CreativeCommonsSampling => "\u{f4f0}",
            Self::CreativeCommonsSamplingPlus => "\u{f4f1}",
            Self::CreativeCommonsShare => "\u{f4f2}",
            Self::CreativeCommonsZero => "\u{f4f3}",
            Self::CriticalRole => "\u{f6c9}",
            Self::Css => "\u{e6a2}",
            Self::Css3 => "\u{f13c}",
            Self::Css3Alt => "\u{f38b}",
            Self::Cuttlefish => "\u{f38c}",
            Self::DAndD => "\u{f38d}",
            Self::DAndDBeyond => "\u{f6ca}",
            Self::Dailymotion => "\u{e052}",
            Self::DartLang => "\u{e693}",
            Self::Dashcube => "\u{f210}",
            Self::Debian => "\u{e60b}",
            Self::Deezer => "\u{e077}",
            Self::Delicious => "\u{f1a5}",
            Self::Deploydog => "\u{f38e}",
            Self::Deskpro => "\u{f38f}",
            Self::Dev => "\u{f6cc}",
            Self::Deviantart => "\u{f1bd}",
            Self::Dhl => "\u{f790}",
            Self::Diaspora => "\u{f791}",
            Self::Digg => "\u{f1a6}",
            Self::DigitalOcean => "\u{f391}",
            Self::Discord => "\u{f392}",
            Self::Discourse => "\u{f393}",
            Self::Dochub => "\u{f394}",
            Self::Docker => "\u{f395}",
            Self::Draft2digital => "\u{f396}",
            Self::Dribbble => "\u{f17d}",
            Self::Dropbox => "\u{f16b}",
            Self::Drupal => "\u{f1a9}",
            Self::Dyalog => "\u{f399}",
            Self::Earlybirds => "\u{f39a}",
            Self::Ebay => "\u{f4f4}",
            Self::Edge => "\u{f282}",
            Self::EdgeLegacy => "\u{e078}",
            Self::Elementor => "\u{f430}",
            Self::Ello => "\u{f5f1}",
            Self::Ember => "\u{f423}",
            Self::Empire => "\u{f1d1}",
            Self::Envira => "\u{f299}",
            Self::Erlang => "\u{f39d}",
            Self::Ethereum => "\u{f42e}",
            Self::Etsy => "\u{f2d7}",
            Self::Evernote => "\u{f839}",
            Self::Expeditedssl => "\u{f23e}",
            Self::Facebook => "\u{f09a}",
            Self::FacebookF => "\u{f39e}",
            Self::FacebookMessenger => "\u{f39f}",
            Self::FantasyFlightGames => "\u{f6dc}",
            Self::Fedex => "\u{f797}",
            Self::Fedora => "\u{f798}",
            Self::Figma => "\u{f799}",
            Self::FilesPinwheel => "\u{e69f}",
            Self::Firefox => "\u{f269}",
            Self::FirefoxBrowser => "\u{e007}",
            Self::FirstOrder => "\u{f2b0}",
            Self::FirstOrderAlt => "\u{f50a}",
            Self::Firstdraft => "\u{f3a1}",
            Self::Flickr => "\u{f16e}",
            Self::Flipboard => "\u{f44d}",
            Self::Flutter => "\u{e694}",
            Self::Fly => "\u{f417}",
            Self::FontAwesome => "\u{f2b4}",
            Self::Fonticons => "\u{f280}",
            Self::FonticonsFi => "\u{f3a2}",
            Self::FortAwesome => "\u{f286}",
            Self::FortAwesomeAlt => "\u{f3a3}",
            Self::Forumbee => "\u{f211}",
            Self::Foursquare => "\u{f180}",
            Self::FreeCodeCamp => "\u{f2c5}",
            Self::Freebsd => "\u{f3a4}",
            Self::Fulcrum => "\u{f50b}",
            Self::GalacticRepublic => "\u{f50c}",
            Self::GalacticSenate => "\u{f50d}",
            Self::GetPocket => "\u{f265}",
            Self::Gg => "\u{f260}",
            Self::GgCircle => "\u{f261}",
            Self::Git => "\u{f1d3}",
            Self::GitAlt => "\u{f841}",
            Self::Github => "\u{f09b}",
            Self::GithubAlt => "\u{f113}",
            Self::Gitkraken => "\u{f3a6}",
            Self::Gitlab => "\u{f296}",
            Self::Gitter => "\u{f426}",
            Self::Glide => "\u{f2a5}",
            Self::GlideG => "\u{f2a6}",
            Self::Gofore => "\u{f3a7}",
            Self::Golang => "\u{e40f}",
            Self::Goodreads => "\u{f3a8}",
            Self::GoodreadsG => "\u{f3a9}",
            Self::Google => "\u{f1a0}",
            Self::GoogleDrive => "\u{f3aa}",
            Self::GooglePay => "\u{e079}",
            Self::GooglePlay => "\u{f3ab}",
            Self::GooglePlus => "\u{f2b3}",
            Self::GooglePlusG => "\u{f0d5}",
            Self::GoogleScholar => "\u{e63b}",
            Self::GoogleWallet => "\u{f1ee}",
            Self::Gratipay => "\u{f184}",
            Self::Grav => "\u{f2d6}",
            Self::Gripfire => "\u{f3ac}",
            Self::Grunt => "\u{f3ad}",
            Self::Guilded => "\u{e07e}",
            Self::Gulp => "\u{f3ae}",
            Self::HackerNews => "\u{f1d4}",
            Self::Hackerrank => "\u{f5f7}",
            Self::Hashnode => "\u{e499}",
            Self::Hips => "\u{f452}",
            Self::HireAHelper => "\u{f3b0}",
            Self::Hive => "\u{e07f}",
            Self::Hooli => "\u{f427}",
            Self::Hornbill => "\u{f592}",
            Self::Hotjar => "\u{f3b1}",
            Self::Houzz => "\u{f27c}",
            Self::Html5 => "\u{f13b}",
            Self::Hubspot => "\u{f3b2}",
            Self::Ideal => "\u{e013}",
            Self::Imdb => "\u{f2d8}",
            Self::Instagram => "\u{f16d}",
            Self::Instalod => "\u{e081}",
            Self::Intercom => "\u{f7af}",
            Self::InternetExplorer => "\u{f26b}",
            Self::Invision => "\u{f7b0}",
            Self::Ioxhost => "\u{f208}",
            Self::ItchIo => "\u{f83a}",
            Self::Itunes => "\u{f3b4}",
            Self::ItunesNote => "\u{f3b5}",
            Self::Java => "\u{f4e4}",
            Self::JediOrder => "\u{f50e}",
            Self::Jenkins => "\u{f3b6}",
            Self::Jira => "\u{f7b1}",
            Self::Joget => "\u{f3b7}",
            Self::Joomla => "\u{f1aa}",
            Self::Js => "\u{f3b8}",
            Self::Jsfiddle => "\u{f1cc}",
            Self::Jxl => "\u{e67b}",
            Self::Kaggle => "\u{f5fa}",
            Self::Keybase => "\u{f4f5}",
            Self::Keycdn => "\u{f3ba}",
            Self::Kickstarter => "\u{f3bb}",
            Self::KickstarterK => "\u{f3bc}",
            Self::Korvue => "\u{f42f}",
            Self::Laravel => "\u{f3bd}",
            Self::Lastfm => "\u{f202}",
            Self::Leanpub => "\u{f212}",
            Self::Less => "\u{f41d}",
            Self::Letterboxd => "\u{e62d}",
            Self::Line => "\u{f3c0}",
            Self::Linkedin => "\u{f08c}",
            Self::LinkedinIn => "\u{f0e1}",
            Self::Linode => "\u{f2b8}",
            Self::Linux => "\u{f17c}",
            Self::Lyft => "\u{f3c3}",
            Self::Magento => "\u{f3c4}",
            Self::Mailchimp => "\u{f59e}",
            Self::Mandalorian => "\u{f50f}",
            Self::Markdown => "\u{f60f}",
            Self::Mastodon => "\u{f4f6}",
            Self::Maxcdn => "\u{f136}",
            Self::Mdb => "\u{f8ca}",
            Self::Medapps => "\u{f3c6}",
            Self::Medium => "\u{f23a}",
            Self::Medrt => "\u{f3c8}",
            Self::Meetup => "\u{f2e0}",
            Self::Megaport => "\u{f5a3}",
            Self::Mendeley => "\u{f7b3}",
            Self::Meta => "\u{e49b}",
            Self::Microblog => "\u{e01a}",
            Self::Microsoft => "\u{f3ca}",
            Self::Mintbit => "\u{e62f}",
            Self::Mix => "\u{f3cb}",
            Self::Mixcloud => "\u{f289}",
            Self::Mixer => "\u{e056}",
            Self::Mizuni => "\u{f3cc}",
            Self::Modx => "\u{f285}",
            Self::Monero => "\u{f3d0}",
            Self::Napster => "\u{f3d2}",
            Self::Neos => "\u{f612}",
            Self::NfcDirectional => "\u{e530}",
            Self::NfcSymbol => "\u{e531}",
            Self::Nimblr => "\u{f5a8}",
            Self::Node => "\u{f419}",
            Self::NodeJs => "\u{f3d3}",
            Self::Npm => "\u{f3d4}",
            Self::Ns8 => "\u{f3d5}",
            Self::Nutritionix => "\u{f3d6}",
            Self::OctopusDeploy => "\u{e082}",
            Self::Odnoklassniki => "\u{f263}",
            Self::Odysee => "\u{e5c6}",
            Self::OldRepublic => "\u{f510}",
            Self::Opencart => "\u{f23d}",
            Self::Openid => "\u{f19b}",
            Self::Opensuse => "\u{e62b}",
            Self::Opera => "\u{f26a}",
            Self::OptinMonster => "\u{f23c}",
            Self::Orcid => "\u{f8d2}",
            Self::Osi => "\u{f41a}",
            Self::Padlet => "\u{e4a0}",
            Self::Page4 => "\u{f3d7}",
            Self::Pagelines => "\u{f18c}",
            Self::Palfed => "\u{f3d8}",
            Self::Patreon => "\u{f3d9}",
            Self::Paypal => "\u{f1ed}",
            Self::Perbyte => "\u{e083}",
            Self::Periscope => "\u{f3da}",
            Self::Phabricator => "\u{f3db}",
            Self::PhoenixFramework => "\u{f3dc}",
            Self::PhoenixSquadron => "\u{f511}",
            Self::Php => "\u{f457}",
            Self::PiedPiper => "\u{f2ae}",
            Self::PiedPiperAlt => "\u{f1a8}",
            Self::PiedPiperHat => "\u{f4e5}",
            Self::PiedPiperPp => "\u{f1a7}",
            Self::Pinterest => "\u{f0d2}",
            Self::PinterestP => "\u{f231}",
            Self::Pix => "\u{e43a}",
            Self::Pixiv => "\u{e640}",
            Self::Playstation => "\u{f3df}",
            Self::ProductHunt => "\u{f288}",
            Self::Pushed => "\u{f3e1}",
            Self::Python => "\u{f3e2}",
            Self::Qq => "\u{f1d6}",
            Self::Quinscape => "\u{f459}",
            Self::Quora => "\u{f2c4}",
            Self::RProject => "\u{f4f7}",
            Self::RaspberryPi => "\u{f7bb}",
            Self::Ravelry => "\u{f2d9}",
            Self::React => "\u{f41b}",
            Self::Reacteurope => "\u{f75d}",
            Self::Readme => "\u{f4d5}",
            Self::Rebel => "\u{f1d0}",
            Self::RedRiver => "\u{f3e3}",
            Self::Reddit => "\u{f1a1}",
            Self::RedditAlien => "\u{f281}",
            Self::Redhat => "\u{f7bc}",
            Self::Renren => "\u{f18b}",
            Self::Replyd => "\u{f3e6}",
            Self::Researchgate => "\u{f4f8}",
            Self::Resolving => "\u{f3e7}",
            Self::Rev => "\u{f5b2}",
            Self::Rocketchat => "\u{f3e8}",
            Self::Rockrms => "\u{f3e9}",
            Self::Rust => "\u{e07a}",
            Self::Safari => "\u{f267}",
            Self::Salesforce => "\u{f83b}",
            Self::Sass => "\u{f41e}",
            Self::Schlix => "\u{f3ea}",
            Self::Screenpal => "\u{e570}",
            Self::Scribd => "\u{f28a}",
            Self::Searchengin => "\u{f3eb}",
            Self::Sellcast => "\u{f2da}",
            Self::Sellsy => "\u{f213}",
            Self::Servicestack => "\u{f3ec}",
            Self::Shirtsinbulk => "\u{f214}",
            Self::Shoelace => "\u{e60c}",
            Self::Shopify => "\u{e057}",
            Self::Shopware => "\u{f5b5}",
            Self::SignalMessenger => "\u{e663}",
            Self::Simplybuilt => "\u{f215}",
            Self::Sistrix => "\u{f3ee}",
            Self::Sith => "\u{f512}",
            Self::Sitrox => "\u{e44a}",
            Self::Sketch => "\u{f7c6}",
            Self::Skyatlas => "\u{f216}",
            Self::Skype => "\u{f17e}",
            Self::Slack => "\u{f198}",
            Self::Slideshare => "\u{f1e7}",
            Self::Snapchat => "\u{f2ab}",
            Self::Soundcloud => "\u{f1be}",
            Self::Sourcetree => "\u{f7d3}",
            Self::SpaceAwesome => "\u{e5ac}",
            Self::Speakap => "\u{f3f3}",
            Self::SpeakerDeck => "\u{f83c}",
            Self::Spotify => "\u{f1bc}",
            Self::SquareBehance => "\u{f1b5}",
            Self::SquareBluesky => "\u{e6a3}",
            Self::SquareDribbble => "\u{f397}",
            Self::SquareFacebook => "\u{f082}",
            Self::SquareFontAwesome => "\u{e5ad}",
            Self::SquareFontAwesomeStroke => "\u{f35c}",
            Self::SquareGit => "\u{f1d2}",
            Self::SquareGithub => "\u{f092}",
            Self::SquareGitlab => "\u{e5ae}",
            Self::SquareGooglePlus => "\u{f0d4}",
            Self::SquareHackerNews => "\u{f3af}",
            Self::SquareInstagram => "\u{e055}",
            Self::SquareJs => "\u{f3b9}",
            Self::SquareLastfm => "\u{f203}",
            Self::SquareLetterboxd => "\u{e62e}",
            Self::SquareOdnoklassniki => "\u{f264}",
            Self::SquarePiedPiper => "\u{e01e}",
            Self::SquarePinterest => "\u{f0d3}",
            Self::SquareReddit => "\u{f1a2}",
            Self::SquareSnapchat => "\u{f2ad}",
            Self::SquareSteam => "\u{f1b7}",
            Self::SquareThreads => "\u{e619}",
            Self::SquareTumblr => "\u{f174}",
            Self::SquareTwitter => "\u{f081}",
            Self::SquareUpwork => "\u{e67c}",
            Self::SquareViadeo => "\u{f2aa}",
            Self::SquareVimeo => "\u{f194}",
            Self::SquareWebAwesome => "\u{e683}",
            Self::SquareWebAwesomeStroke => "\u{e684}",
            Self::SquareWhatsapp => "\u{f40c}",
            Self::SquareXTwitter => "\u{e61a}",
            Self::SquareXing => "\u{f169}",
            Self::SquareYoutube => "\u{f431}",
            Self::Squarespace => "\u{f5be}",
            Self::StackExchange => "\u{f18d}",
            Self::StackOverflow => "\u{f16c}",
            Self::Stackpath => "\u{f842}",
            Self::Staylinked => "\u{f3f5}",
            Self::Steam => "\u{f1b6}",
            Self::SteamSymbol => "\u{f3f6}",
            Self::StickerMule => "\u{f3f7}",
            Self::Strava => "\u{f428}",
            Self::Stripe => "\u{f429}",
            Self::StripeS => "\u{f42a}",
            Self::Stubber => "\u{e5c7}",
            Self::Studiovinari => "\u{f3f8}",
            Self::Stumbleupon => "\u{f1a4}",
            Self::StumbleuponCircle => "\u{f1a3}",
            Self::Superpowers => "\u{f2dd}",
            Self::Supple => "\u{f3f9}",
            Self::Suse => "\u{f7d6}",
            Self::Swift => "\u{f8e1}",
            Self::Symfony => "\u{f83d}",
            Self::Teamspeak => "\u{f4f9}",
            Self::Telegram => "\u{f2c6}",
            Self::TencentWeibo => "\u{f1d5}",
            Self::TheRedYeti => "\u{f69d}",
            Self::Themeco => "\u{f5c6}",
            Self::Themeisle => "\u{f2b2}",
            Self::ThinkPeaks => "\u{f731}",
            Self::Threads => "\u{e618}",
            Self::Tiktok => "\u{e07b}",
            Self::TradeFederation => "\u{f513}",
            Self::Trello => "\u{f181}",
            Self::Tumblr => "\u{f173}",
            Self::Twitch => "\u{f1e8}",
            Self::Twitter => "\u{f099}",
            Self::Typo3 => "\u{f42b}",
            Self::Uber => "\u{f402}",
            Self::Ubuntu => "\u{f7df}",
            Self::Uikit => "\u{f403}",
            Self::Umbraco => "\u{f8e8}",
            Self::Uncharted => "\u{e084}",
            Self::Uniregistry => "\u{f404}",
            Self::Unity => "\u{e049}",
            Self::Unsplash => "\u{e07c}",
            Self::Untappd => "\u{f405}",
            Self::Ups => "\u{f7e0}",
            Self::Upwork => "\u{e641}",
            Self::Usb => "\u{f287}",
            Self::Usps => "\u{f7e1}",
            Self::Ussunnah => "\u{f407}",
            Self::Vaadin => "\u{f408}",
            Self::Viacoin => "\u{f237}",
            Self::Viadeo => "\u{f2a9}",
            Self::Viber => "\u{f409}",
            Self::Vimeo => "\u{f40a}",
            Self::VimeoV => "\u{f27d}",
            Self::Vine => "\u{f1ca}",
            Self::Vk => "\u{f189}",
            Self::Vnv => "\u{f40b}",
            Self::Vuejs => "\u{f41f}",
            Self::WatchmanMonitoring => "\u{e087}",
            Self::Waze => "\u{f83f}",
            Self::WebAwesome => "\u{e682}",
            Self::Webflow => "\u{e65c}",
            Self::Weebly => "\u{f5cc}",
            Self::Weibo => "\u{f18a}",
            Self::Weixin => "\u{f1d7}",
            Self::Whatsapp => "\u{f232}",
            Self::Whmcs => "\u{f40d}",
            Self::WikipediaW => "\u{f266}",
            Self::Windows => "\u{f17a}",
            Self::Wirsindhandwerk => "\u{e2d0}",
            Self::Wix => "\u{f5cf}",
            Self::WizardsOfTheCoast => "\u{f730}",
            Self::Wodu => "\u{e088}",
            Self::WolfPackBattalion => "\u{f514}",
            Self::Wordpress => "\u{f19a}",
            Self::WordpressSimple => "\u{f411}",
            Self::Wpbeginner => "\u{f297}",
            Self::Wpexplorer => "\u{f2de}",
            Self::Wpforms => "\u{f298}",
            Self::Wpressr => "\u{f3e4}",
            Self::XTwitter => "\u{e61b}",
            Self::Xbox => "\u{f412}",
            Self::Xing => "\u{f168}",
            Self::YCombinator => "\u{f23b}",
            Self::Yahoo => "\u{f19e}",
            Self::Yammer => "\u{f840}",
            Self::Yandex => "\u{f413}",
            Self::YandexInternational => "\u{f414}",
            Self::Yarn => "\u{f7e3}",
            Self::Yelp => "\u{f1e9}",
            Self::Yoast => "\u{f2b1}",
            Self::Youtube => "\u{f167}",
            Self::Zhihu => "\u{f63f}",
        }
    }
}

pub fn brands<'a>(c: FontAwesomeBrands) -> Text<'a> {
    text(c.to_string().to_owned()).font(FONT)
}

const FONT: Font = Font {
    family: Family::Name("Font Awesome 6 Brands"),
    weight: iced::font::Weight::Normal,
    ..Font::DEFAULT
};
