use iced::{Font, font::Family};

use iced::widget::{Text, text};

pub enum FontAwesomeRegular {
    AddressBook,
    AddressCard,
    Bell,
    BellSlash,
    Bookmark,
    Building,
    Calendar,
    CalendarCheck,
    CalendarDays,
    CalendarMinus,
    CalendarPlus,
    CalendarXmark,
    ChartBar,
    ChessBishop,
    ChessKing,
    ChessKnight,
    ChessPawn,
    ChessQueen,
    ChessRook,
    Circle,
    CircleCheck,
    CircleDot,
    CircleDown,
    CircleLeft,
    CirclePause,
    CirclePlay,
    CircleQuestion,
    CircleRight,
    CircleStop,
    CircleUp,
    CircleUser,
    CircleXmark,
    Clipboard,
    Clock,
    Clone,
    ClosedCaptioning,
    Comment,
    CommentDots,
    Comments,
    Compass,
    Copy,
    Copyright,
    CreditCard,
    Envelope,
    EnvelopeOpen,
    Eye,
    EyeSlash,
    FaceAngry,
    FaceDizzy,
    FaceFlushed,
    FaceFrown,
    FaceFrownOpen,
    FaceGrimace,
    FaceGrin,
    FaceGrinBeam,
    FaceGrinBeamSweat,
    FaceGrinHearts,
    FaceGrinSquint,
    FaceGrinSquintTears,
    FaceGrinStars,
    FaceGrinTears,
    FaceGrinTongue,
    FaceGrinTongueSquint,
    FaceGrinTongueWink,
    FaceGrinWide,
    FaceGrinWink,
    FaceKiss,
    FaceKissBeam,
    FaceKissWinkHeart,
    FaceLaugh,
    FaceLaughBeam,
    FaceLaughSquint,
    FaceLaughWink,
    FaceMeh,
    FaceMehBlank,
    FaceRollingEyes,
    FaceSadCry,
    FaceSadTear,
    FaceSmile,
    FaceSmileBeam,
    FaceSmileWink,
    FaceSurprise,
    FaceTired,
    File,
    FileAudio,
    FileCode,
    FileExcel,
    FileImage,
    FileLines,
    FilePdf,
    FilePowerpoint,
    FileVideo,
    FileWord,
    FileZipper,
    Flag,
    FloppyDisk,
    Folder,
    FolderClosed,
    FolderOpen,
    FontAwesome,
    Futbol,
    Gem,
    Hand,
    HandBackFist,
    HandLizard,
    HandPeace,
    HandPointDown,
    HandPointLeft,
    HandPointRight,
    HandPointUp,
    HandPointer,
    HandScissors,
    HandSpock,
    Handshake,
    HardDrive,
    Heart,
    Hospital,
    Hourglass,
    HourglassHalf,
    IdBadge,
    IdCard,
    Image,
    Images,
    Keyboard,
    Lemon,
    LifeRing,
    Lightbulb,
    Map,
    Message,
    MoneyBill1,
    Moon,
    Newspaper,
    NoteSticky,
    ObjectGroup,
    ObjectUngroup,
    PaperPlane,
    Paste,
    PenToSquare,
    RectangleList,
    RectangleXmark,
    Registered,
    ShareFromSquare,
    Snowflake,
    Square,
    SquareCaretDown,
    SquareCaretLeft,
    SquareCaretRight,
    SquareCaretUp,
    SquareCheck,
    SquareFull,
    SquareMinus,
    SquarePlus,
    Star,
    StarHalf,
    StarHalfStroke,
    Sun,
    ThumbsDown,
    ThumbsUp,
    TrashCan,
    User,
    WindowMaximize,
    WindowMinimize,
    WindowRestore,
}

impl FontAwesomeRegular {
    pub fn to_string(&self) -> String {
        match self {
            Self::AddressBook => "\u{f2b9}".to_owned(),
            Self::AddressCard => "\u{f2bb}".to_owned(),
            Self::Bell => "\u{f0f3}".to_owned(),
            Self::BellSlash => "\u{f1f6}".to_owned(),
            Self::Bookmark => "\u{f02e}".to_owned(),
            Self::Building => "\u{f1ad}".to_owned(),
            Self::Calendar => "\u{f133}".to_owned(),
            Self::CalendarCheck => "\u{f274}".to_owned(),
            Self::CalendarDays => "\u{f073}".to_owned(),
            Self::CalendarMinus => "\u{f272}".to_owned(),
            Self::CalendarPlus => "\u{f271}".to_owned(),
            Self::CalendarXmark => "\u{f273}".to_owned(),
            Self::ChartBar => "\u{f080}".to_owned(),
            Self::ChessBishop => "\u{f43a}".to_owned(),
            Self::ChessKing => "\u{f43f}".to_owned(),
            Self::ChessKnight => "\u{f441}".to_owned(),
            Self::ChessPawn => "\u{f443}".to_owned(),
            Self::ChessQueen => "\u{f445}".to_owned(),
            Self::ChessRook => "\u{f447}".to_owned(),
            Self::Circle => "\u{f111}".to_owned(),
            Self::CircleCheck => "\u{f058}".to_owned(),
            Self::CircleDot => "\u{f192}".to_owned(),
            Self::CircleDown => "\u{f358}".to_owned(),
            Self::CircleLeft => "\u{f359}".to_owned(),
            Self::CirclePause => "\u{f28b}".to_owned(),
            Self::CirclePlay => "\u{f144}".to_owned(),
            Self::CircleQuestion => "\u{f059}".to_owned(),
            Self::CircleRight => "\u{f35a}".to_owned(),
            Self::CircleStop => "\u{f28d}".to_owned(),
            Self::CircleUp => "\u{f35b}".to_owned(),
            Self::CircleUser => "\u{f2bd}".to_owned(),
            Self::CircleXmark => "\u{f057}".to_owned(),
            Self::Clipboard => "\u{f328}".to_owned(),
            Self::Clock => "\u{f017}".to_owned(),
            Self::Clone => "\u{f24d}".to_owned(),
            Self::ClosedCaptioning => "\u{f20a}".to_owned(),
            Self::Comment => "\u{f075}".to_owned(),
            Self::CommentDots => "\u{f4ad}".to_owned(),
            Self::Comments => "\u{f086}".to_owned(),
            Self::Compass => "\u{f14e}".to_owned(),
            Self::Copy => "\u{f0c5}".to_owned(),
            Self::Copyright => "\u{f1f9}".to_owned(),
            Self::CreditCard => "\u{f09d}".to_owned(),
            Self::Envelope => "\u{f0e0}".to_owned(),
            Self::EnvelopeOpen => "\u{f2b6}".to_owned(),
            Self::Eye => "\u{f06e}".to_owned(),
            Self::EyeSlash => "\u{f070}".to_owned(),
            Self::FaceAngry => "\u{f556}".to_owned(),
            Self::FaceDizzy => "\u{f567}".to_owned(),
            Self::FaceFlushed => "\u{f579}".to_owned(),
            Self::FaceFrown => "\u{f119}".to_owned(),
            Self::FaceFrownOpen => "\u{f57a}".to_owned(),
            Self::FaceGrimace => "\u{f57f}".to_owned(),
            Self::FaceGrin => "\u{f580}".to_owned(),
            Self::FaceGrinBeam => "\u{f582}".to_owned(),
            Self::FaceGrinBeamSweat => "\u{f583}".to_owned(),
            Self::FaceGrinHearts => "\u{f584}".to_owned(),
            Self::FaceGrinSquint => "\u{f585}".to_owned(),
            Self::FaceGrinSquintTears => "\u{f586}".to_owned(),
            Self::FaceGrinStars => "\u{f587}".to_owned(),
            Self::FaceGrinTears => "\u{f588}".to_owned(),
            Self::FaceGrinTongue => "\u{f589}".to_owned(),
            Self::FaceGrinTongueSquint => "\u{f58a}".to_owned(),
            Self::FaceGrinTongueWink => "\u{f58b}".to_owned(),
            Self::FaceGrinWide => "\u{f581}".to_owned(),
            Self::FaceGrinWink => "\u{f58c}".to_owned(),
            Self::FaceKiss => "\u{f596}".to_owned(),
            Self::FaceKissBeam => "\u{f597}".to_owned(),
            Self::FaceKissWinkHeart => "\u{f598}".to_owned(),
            Self::FaceLaugh => "\u{f599}".to_owned(),
            Self::FaceLaughBeam => "\u{f59a}".to_owned(),
            Self::FaceLaughSquint => "\u{f59b}".to_owned(),
            Self::FaceLaughWink => "\u{f59c}".to_owned(),
            Self::FaceMeh => "\u{f11a}".to_owned(),
            Self::FaceMehBlank => "\u{f5a4}".to_owned(),
            Self::FaceRollingEyes => "\u{f5a5}".to_owned(),
            Self::FaceSadCry => "\u{f5b3}".to_owned(),
            Self::FaceSadTear => "\u{f5b4}".to_owned(),
            Self::FaceSmile => "\u{f118}".to_owned(),
            Self::FaceSmileBeam => "\u{f5b8}".to_owned(),
            Self::FaceSmileWink => "\u{f4da}".to_owned(),
            Self::FaceSurprise => "\u{f5c2}".to_owned(),
            Self::FaceTired => "\u{f5c8}".to_owned(),
            Self::File => "\u{f15b}".to_owned(),
            Self::FileAudio => "\u{f1c7}".to_owned(),
            Self::FileCode => "\u{f1c9}".to_owned(),
            Self::FileExcel => "\u{f1c3}".to_owned(),
            Self::FileImage => "\u{f1c5}".to_owned(),
            Self::FileLines => "\u{f15c}".to_owned(),
            Self::FilePdf => "\u{f1c1}".to_owned(),
            Self::FilePowerpoint => "\u{f1c4}".to_owned(),
            Self::FileVideo => "\u{f1c8}".to_owned(),
            Self::FileWord => "\u{f1c2}".to_owned(),
            Self::FileZipper => "\u{f1c6}".to_owned(),
            Self::Flag => "\u{f024}".to_owned(),
            Self::FloppyDisk => "\u{f0c7}".to_owned(),
            Self::Folder => "\u{f07b}".to_owned(),
            Self::FolderClosed => "\u{e185}".to_owned(),
            Self::FolderOpen => "\u{f07c}".to_owned(),
            Self::FontAwesome => "\u{f2b4}".to_owned(),
            Self::Futbol => "\u{f1e3}".to_owned(),
            Self::Gem => "\u{f3a5}".to_owned(),
            Self::Hand => "\u{f256}".to_owned(),
            Self::HandBackFist => "\u{f255}".to_owned(),
            Self::HandLizard => "\u{f258}".to_owned(),
            Self::HandPeace => "\u{f25b}".to_owned(),
            Self::HandPointDown => "\u{f0a7}".to_owned(),
            Self::HandPointLeft => "\u{f0a5}".to_owned(),
            Self::HandPointRight => "\u{f0a4}".to_owned(),
            Self::HandPointUp => "\u{f0a6}".to_owned(),
            Self::HandPointer => "\u{f25a}".to_owned(),
            Self::HandScissors => "\u{f257}".to_owned(),
            Self::HandSpock => "\u{f259}".to_owned(),
            Self::Handshake => "\u{f2b5}".to_owned(),
            Self::HardDrive => "\u{f0a0}".to_owned(),
            Self::Heart => "\u{f004}".to_owned(),
            Self::Hospital => "\u{f0f8}".to_owned(),
            Self::Hourglass => "\u{f254}".to_owned(),
            Self::HourglassHalf => "\u{f252}".to_owned(),
            Self::IdBadge => "\u{f2c1}".to_owned(),
            Self::IdCard => "\u{f2c2}".to_owned(),
            Self::Image => "\u{f03e}".to_owned(),
            Self::Images => "\u{f302}".to_owned(),
            Self::Keyboard => "\u{f11c}".to_owned(),
            Self::Lemon => "\u{f094}".to_owned(),
            Self::LifeRing => "\u{f1cd}".to_owned(),
            Self::Lightbulb => "\u{f0eb}".to_owned(),
            Self::Map => "\u{f279}".to_owned(),
            Self::Message => "\u{f27a}".to_owned(),
            Self::MoneyBill1 => "\u{f3d1}".to_owned(),
            Self::Moon => "\u{f186}".to_owned(),
            Self::Newspaper => "\u{f1ea}".to_owned(),
            Self::NoteSticky => "\u{f249}".to_owned(),
            Self::ObjectGroup => "\u{f247}".to_owned(),
            Self::ObjectUngroup => "\u{f248}".to_owned(),
            Self::PaperPlane => "\u{f1d8}".to_owned(),
            Self::Paste => "\u{f0ea}".to_owned(),
            Self::PenToSquare => "\u{f044}".to_owned(),
            Self::RectangleList => "\u{f022}".to_owned(),
            Self::RectangleXmark => "\u{f410}".to_owned(),
            Self::Registered => "\u{f25d}".to_owned(),
            Self::ShareFromSquare => "\u{f14d}".to_owned(),
            Self::Snowflake => "\u{f2dc}".to_owned(),
            Self::Square => "\u{f0c8}".to_owned(),
            Self::SquareCaretDown => "\u{f150}".to_owned(),
            Self::SquareCaretLeft => "\u{f191}".to_owned(),
            Self::SquareCaretRight => "\u{f152}".to_owned(),
            Self::SquareCaretUp => "\u{f151}".to_owned(),
            Self::SquareCheck => "\u{f14a}".to_owned(),
            Self::SquareFull => "\u{f45c}".to_owned(),
            Self::SquareMinus => "\u{f146}".to_owned(),
            Self::SquarePlus => "\u{f0fe}".to_owned(),
            Self::Star => "\u{f005}".to_owned(),
            Self::StarHalf => "\u{f089}".to_owned(),
            Self::StarHalfStroke => "\u{f5c0}".to_owned(),
            Self::Sun => "\u{f185}".to_owned(),
            Self::ThumbsDown => "\u{f165}".to_owned(),
            Self::ThumbsUp => "\u{f164}".to_owned(),
            Self::TrashCan => "\u{f2ed}".to_owned(),
            Self::User => "\u{f007}".to_owned(),
            Self::WindowMaximize => "\u{f2d0}".to_owned(),
            Self::WindowMinimize => "\u{f2d1}".to_owned(),
            Self::WindowRestore => "\u{f2d2}".to_owned(),
        }
    }
}

pub fn regular<'a>(c: FontAwesomeRegular) -> Text<'a> {
    text(c.to_string()).font(FONTAWESOMEREGULAR_FONT)
}

const FONTAWESOMEREGULAR_FONT: Font = Font {
    family: Family::Name("Font Awesome 6 Free"),
    weight: iced::font::Weight::Normal,
    ..Font::DEFAULT
};
