use iced::{Font, font::Family};

use iced::widget::{Text, text};

pub enum FontAwesomeRegular {
    AddressBook,
    AddressCard,
    Bell,
    BellSlash,
    Bookmark,
    Building,
    Calendar,
    CalendarCheck,
    CalendarDays,
    CalendarMinus,
    CalendarPlus,
    CalendarXmark,
    ChartBar,
    ChessBishop,
    ChessKing,
    ChessKnight,
    ChessPawn,
    ChessQueen,
    ChessRook,
    Circle,
    CircleCheck,
    CircleDot,
    CircleDown,
    CircleLeft,
    CirclePause,
    CirclePlay,
    CircleQuestion,
    CircleRight,
    CircleStop,
    CircleUp,
    CircleUser,
    CircleXmark,
    Clipboard,
    Clock,
    Clone,
    ClosedCaptioning,
    Comment,
    CommentDots,
    Comments,
    Compass,
    Copy,
    Copyright,
    CreditCard,
    Envelope,
    EnvelopeOpen,
    Eye,
    EyeSlash,
    FaceAngry,
    FaceDizzy,
    FaceFlushed,
    FaceFrown,
    FaceFrownOpen,
    FaceGrimace,
    FaceGrin,
    FaceGrinBeam,
    FaceGrinBeamSweat,
    FaceGrinHearts,
    FaceGrinSquint,
    FaceGrinSquintTears,
    FaceGrinStars,
    FaceGrinTears,
    FaceGrinTongue,
    FaceGrinTongueSquint,
    FaceGrinTongueWink,
    FaceGrinWide,
    FaceGrinWink,
    FaceKiss,
    FaceKissBeam,
    FaceKissWinkHeart,
    FaceLaugh,
    FaceLaughBeam,
    FaceLaughSquint,
    FaceLaughWink,
    FaceMeh,
    FaceMehBlank,
    FaceRollingEyes,
    FaceSadCry,
    FaceSadTear,
    FaceSmile,
    FaceSmileBeam,
    FaceSmileWink,
    FaceSurprise,
    FaceTired,
    File,
    FileAudio,
    FileCode,
    FileExcel,
    FileImage,
    FileLines,
    FilePdf,
    FilePowerpoint,
    FileVideo,
    FileWord,
    FileZipper,
    Flag,
    FloppyDisk,
    Folder,
    FolderClosed,
    FolderOpen,
    FontAwesome,
    Futbol,
    Gem,
    Hand,
    HandBackFist,
    HandLizard,
    HandPeace,
    HandPointDown,
    HandPointLeft,
    HandPointRight,
    HandPointUp,
    HandPointer,
    HandScissors,
    HandSpock,
    Handshake,
    HardDrive,
    Heart,
    Hospital,
    Hourglass,
    HourglassHalf,
    IdBadge,
    IdCard,
    Image,
    Images,
    Keyboard,
    Lemon,
    LifeRing,
    Lightbulb,
    Map,
    Message,
    MoneyBill1,
    Moon,
    Newspaper,
    NoteSticky,
    ObjectGroup,
    ObjectUngroup,
    PaperPlane,
    Paste,
    PenToSquare,
    RectangleList,
    RectangleXmark,
    Registered,
    ShareFromSquare,
    Snowflake,
    Square,
    SquareCaretDown,
    SquareCaretLeft,
    SquareCaretRight,
    SquareCaretUp,
    SquareCheck,
    SquareFull,
    SquareMinus,
    SquarePlus,
    Star,
    StarHalf,
    StarHalfStroke,
    Sun,
    ThumbsDown,
    ThumbsUp,
    TrashCan,
    User,
    WindowMaximize,
    WindowMinimize,
    WindowRestore,
}

impl FontAwesomeRegular {
    pub fn to_unicode(&self) -> &str {
        match self {
            Self::AddressBook => "\u{f2b9}",
            Self::AddressCard => "\u{f2bb}",
            Self::Bell => "\u{f0f3}",
            Self::BellSlash => "\u{f1f6}",
            Self::Bookmark => "\u{f02e}",
            Self::Building => "\u{f1ad}",
            Self::Calendar => "\u{f133}",
            Self::CalendarCheck => "\u{f274}",
            Self::CalendarDays => "\u{f073}",
            Self::CalendarMinus => "\u{f272}",
            Self::CalendarPlus => "\u{f271}",
            Self::CalendarXmark => "\u{f273}",
            Self::ChartBar => "\u{f080}",
            Self::ChessBishop => "\u{f43a}",
            Self::ChessKing => "\u{f43f}",
            Self::ChessKnight => "\u{f441}",
            Self::ChessPawn => "\u{f443}",
            Self::ChessQueen => "\u{f445}",
            Self::ChessRook => "\u{f447}",
            Self::Circle => "\u{f111}",
            Self::CircleCheck => "\u{f058}",
            Self::CircleDot => "\u{f192}",
            Self::CircleDown => "\u{f358}",
            Self::CircleLeft => "\u{f359}",
            Self::CirclePause => "\u{f28b}",
            Self::CirclePlay => "\u{f144}",
            Self::CircleQuestion => "\u{f059}",
            Self::CircleRight => "\u{f35a}",
            Self::CircleStop => "\u{f28d}",
            Self::CircleUp => "\u{f35b}",
            Self::CircleUser => "\u{f2bd}",
            Self::CircleXmark => "\u{f057}",
            Self::Clipboard => "\u{f328}",
            Self::Clock => "\u{f017}",
            Self::Clone => "\u{f24d}",
            Self::ClosedCaptioning => "\u{f20a}",
            Self::Comment => "\u{f075}",
            Self::CommentDots => "\u{f4ad}",
            Self::Comments => "\u{f086}",
            Self::Compass => "\u{f14e}",
            Self::Copy => "\u{f0c5}",
            Self::Copyright => "\u{f1f9}",
            Self::CreditCard => "\u{f09d}",
            Self::Envelope => "\u{f0e0}",
            Self::EnvelopeOpen => "\u{f2b6}",
            Self::Eye => "\u{f06e}",
            Self::EyeSlash => "\u{f070}",
            Self::FaceAngry => "\u{f556}",
            Self::FaceDizzy => "\u{f567}",
            Self::FaceFlushed => "\u{f579}",
            Self::FaceFrown => "\u{f119}",
            Self::FaceFrownOpen => "\u{f57a}",
            Self::FaceGrimace => "\u{f57f}",
            Self::FaceGrin => "\u{f580}",
            Self::FaceGrinBeam => "\u{f582}",
            Self::FaceGrinBeamSweat => "\u{f583}",
            Self::FaceGrinHearts => "\u{f584}",
            Self::FaceGrinSquint => "\u{f585}",
            Self::FaceGrinSquintTears => "\u{f586}",
            Self::FaceGrinStars => "\u{f587}",
            Self::FaceGrinTears => "\u{f588}",
            Self::FaceGrinTongue => "\u{f589}",
            Self::FaceGrinTongueSquint => "\u{f58a}",
            Self::FaceGrinTongueWink => "\u{f58b}",
            Self::FaceGrinWide => "\u{f581}",
            Self::FaceGrinWink => "\u{f58c}",
            Self::FaceKiss => "\u{f596}",
            Self::FaceKissBeam => "\u{f597}",
            Self::FaceKissWinkHeart => "\u{f598}",
            Self::FaceLaugh => "\u{f599}",
            Self::FaceLaughBeam => "\u{f59a}",
            Self::FaceLaughSquint => "\u{f59b}",
            Self::FaceLaughWink => "\u{f59c}",
            Self::FaceMeh => "\u{f11a}",
            Self::FaceMehBlank => "\u{f5a4}",
            Self::FaceRollingEyes => "\u{f5a5}",
            Self::FaceSadCry => "\u{f5b3}",
            Self::FaceSadTear => "\u{f5b4}",
            Self::FaceSmile => "\u{f118}",
            Self::FaceSmileBeam => "\u{f5b8}",
            Self::FaceSmileWink => "\u{f4da}",
            Self::FaceSurprise => "\u{f5c2}",
            Self::FaceTired => "\u{f5c8}",
            Self::File => "\u{f15b}",
            Self::FileAudio => "\u{f1c7}",
            Self::FileCode => "\u{f1c9}",
            Self::FileExcel => "\u{f1c3}",
            Self::FileImage => "\u{f1c5}",
            Self::FileLines => "\u{f15c}",
            Self::FilePdf => "\u{f1c1}",
            Self::FilePowerpoint => "\u{f1c4}",
            Self::FileVideo => "\u{f1c8}",
            Self::FileWord => "\u{f1c2}",
            Self::FileZipper => "\u{f1c6}",
            Self::Flag => "\u{f024}",
            Self::FloppyDisk => "\u{f0c7}",
            Self::Folder => "\u{f07b}",
            Self::FolderClosed => "\u{e185}",
            Self::FolderOpen => "\u{f07c}",
            Self::FontAwesome => "\u{f2b4}",
            Self::Futbol => "\u{f1e3}",
            Self::Gem => "\u{f3a5}",
            Self::Hand => "\u{f256}",
            Self::HandBackFist => "\u{f255}",
            Self::HandLizard => "\u{f258}",
            Self::HandPeace => "\u{f25b}",
            Self::HandPointDown => "\u{f0a7}",
            Self::HandPointLeft => "\u{f0a5}",
            Self::HandPointRight => "\u{f0a4}",
            Self::HandPointUp => "\u{f0a6}",
            Self::HandPointer => "\u{f25a}",
            Self::HandScissors => "\u{f257}",
            Self::HandSpock => "\u{f259}",
            Self::Handshake => "\u{f2b5}",
            Self::HardDrive => "\u{f0a0}",
            Self::Heart => "\u{f004}",
            Self::Hospital => "\u{f0f8}",
            Self::Hourglass => "\u{f254}",
            Self::HourglassHalf => "\u{f252}",
            Self::IdBadge => "\u{f2c1}",
            Self::IdCard => "\u{f2c2}",
            Self::Image => "\u{f03e}",
            Self::Images => "\u{f302}",
            Self::Keyboard => "\u{f11c}",
            Self::Lemon => "\u{f094}",
            Self::LifeRing => "\u{f1cd}",
            Self::Lightbulb => "\u{f0eb}",
            Self::Map => "\u{f279}",
            Self::Message => "\u{f27a}",
            Self::MoneyBill1 => "\u{f3d1}",
            Self::Moon => "\u{f186}",
            Self::Newspaper => "\u{f1ea}",
            Self::NoteSticky => "\u{f249}",
            Self::ObjectGroup => "\u{f247}",
            Self::ObjectUngroup => "\u{f248}",
            Self::PaperPlane => "\u{f1d8}",
            Self::Paste => "\u{f0ea}",
            Self::PenToSquare => "\u{f044}",
            Self::RectangleList => "\u{f022}",
            Self::RectangleXmark => "\u{f410}",
            Self::Registered => "\u{f25d}",
            Self::ShareFromSquare => "\u{f14d}",
            Self::Snowflake => "\u{f2dc}",
            Self::Square => "\u{f0c8}",
            Self::SquareCaretDown => "\u{f150}",
            Self::SquareCaretLeft => "\u{f191}",
            Self::SquareCaretRight => "\u{f152}",
            Self::SquareCaretUp => "\u{f151}",
            Self::SquareCheck => "\u{f14a}",
            Self::SquareFull => "\u{f45c}",
            Self::SquareMinus => "\u{f146}",
            Self::SquarePlus => "\u{f0fe}",
            Self::Star => "\u{f005}",
            Self::StarHalf => "\u{f089}",
            Self::StarHalfStroke => "\u{f5c0}",
            Self::Sun => "\u{f185}",
            Self::ThumbsDown => "\u{f165}",
            Self::ThumbsUp => "\u{f164}",
            Self::TrashCan => "\u{f2ed}",
            Self::User => "\u{f007}",
            Self::WindowMaximize => "\u{f2d0}",
            Self::WindowMinimize => "\u{f2d1}",
            Self::WindowRestore => "\u{f2d2}",
        }
    }
}

pub fn regular<'a>(c: FontAwesomeRegular) -> Text<'a> {
    text(c.to_unicode().to_owned()).font(FONT)
}

const FONT: Font = Font {
    family: Family::Name("Font Awesome 6 Free"),
    weight: iced::font::Weight::Normal,
    ..Font::DEFAULT
};
