use iced::{Font, font::Family};

use iced::widget::{Text, text};

pub enum FontAwesomeSolid {
    A,
    AddressBook,
    AddressCard,
    AlignCenter,
    AlignJustify,
    AlignLeft,
    AlignRight,
    Anchor,
    AnchorCircleCheck,
    AnchorCircleExclamation,
    AnchorCircleXmark,
    AnchorLock,
    AngleDown,
    AngleLeft,
    AngleRight,
    AngleUp,
    AnglesDown,
    AnglesLeft,
    AnglesRight,
    AnglesUp,
    Ankh,
    AppleWhole,
    Archway,
    ArrowDown,
    ArrowDown19,
    ArrowDown91,
    ArrowDownAZ,
    ArrowDownLong,
    ArrowDownShortWide,
    ArrowDownUpAcrossLine,
    ArrowDownUpLock,
    ArrowDownWideShort,
    ArrowDownZA,
    ArrowLeft,
    ArrowLeftLong,
    ArrowPointer,
    ArrowRight,
    ArrowRightArrowLeft,
    ArrowRightFromBracket,
    ArrowRightLong,
    ArrowRightToBracket,
    ArrowRightToCity,
    ArrowRotateLeft,
    ArrowRotateRight,
    ArrowTrendDown,
    ArrowTrendUp,
    ArrowTurnDown,
    ArrowTurnUp,
    ArrowUp,
    ArrowUp19,
    ArrowUp91,
    ArrowUpAZ,
    ArrowUpFromBracket,
    ArrowUpFromGroundWater,
    ArrowUpFromWaterPump,
    ArrowUpLong,
    ArrowUpRightDots,
    ArrowUpRightFromSquare,
    ArrowUpShortWide,
    ArrowUpWideShort,
    ArrowUpZA,
    ArrowsDownToLine,
    ArrowsDownToPeople,
    ArrowsLeftRight,
    ArrowsLeftRightToLine,
    ArrowsRotate,
    ArrowsSpin,
    ArrowsSplitUpAndLeft,
    ArrowsToCircle,
    ArrowsToDot,
    ArrowsToEye,
    ArrowsTurnRight,
    ArrowsTurnToDots,
    ArrowsUpDown,
    ArrowsUpDownLeftRight,
    ArrowsUpToLine,
    Asterisk,
    At,
    Atom,
    AudioDescription,
    AustralSign,
    Award,
    B,
    Baby,
    BabyCarriage,
    Backward,
    BackwardFast,
    BackwardStep,
    Bacon,
    Bacteria,
    Bacterium,
    BagShopping,
    Bahai,
    BahtSign,
    Ban,
    BanSmoking,
    Bandage,
    BangladeshiTakaSign,
    Barcode,
    Bars,
    BarsProgress,
    BarsStaggered,
    Baseball,
    BaseballBatBall,
    BasketShopping,
    Basketball,
    Bath,
    BatteryEmpty,
    BatteryFull,
    BatteryHalf,
    BatteryQuarter,
    BatteryThreeQuarters,
    Bed,
    BedPulse,
    BeerMugEmpty,
    Bell,
    BellConcierge,
    BellSlash,
    BezierCurve,
    Bicycle,
    Binoculars,
    Biohazard,
    BitcoinSign,
    Blender,
    BlenderPhone,
    Blog,
    Bold,
    Bolt,
    BoltLightning,
    Bomb,
    Bone,
    Bong,
    Book,
    BookAtlas,
    BookBible,
    BookBookmark,
    BookJournalWhills,
    BookMedical,
    BookOpen,
    BookOpenReader,
    BookQuran,
    BookSkull,
    BookTanakh,
    Bookmark,
    BorderAll,
    BorderNone,
    BorderTopLeft,
    BoreHole,
    BottleDroplet,
    BottleWater,
    BowlFood,
    BowlRice,
    BowlingBall,
    Box,
    BoxArchive,
    BoxOpen,
    BoxTissue,
    BoxesPacking,
    BoxesStacked,
    Braille,
    Brain,
    BrazilianRealSign,
    BreadSlice,
    Bridge,
    BridgeCircleCheck,
    BridgeCircleExclamation,
    BridgeCircleXmark,
    BridgeLock,
    BridgeWater,
    Briefcase,
    BriefcaseMedical,
    Broom,
    BroomBall,
    Brush,
    Bucket,
    Bug,
    BugSlash,
    Bugs,
    Building,
    BuildingCircleArrowRight,
    BuildingCircleCheck,
    BuildingCircleExclamation,
    BuildingCircleXmark,
    BuildingColumns,
    BuildingFlag,
    BuildingLock,
    BuildingNgo,
    BuildingShield,
    BuildingUn,
    BuildingUser,
    BuildingWheat,
    Bullhorn,
    Bullseye,
    Burger,
    Burst,
    Bus,
    BusSimple,
    BusinessTime,
    C,
    CableCar,
    CakeCandles,
    Calculator,
    Calendar,
    CalendarCheck,
    CalendarDay,
    CalendarDays,
    CalendarMinus,
    CalendarPlus,
    CalendarWeek,
    CalendarXmark,
    Camera,
    CameraRetro,
    CameraRotate,
    Campground,
    CandyCane,
    Cannabis,
    Capsules,
    Car,
    CarBattery,
    CarBurst,
    CarOn,
    CarRear,
    CarSide,
    CarTunnel,
    Caravan,
    CaretDown,
    CaretLeft,
    CaretRight,
    CaretUp,
    Carrot,
    CartArrowDown,
    CartFlatbed,
    CartFlatbedSuitcase,
    CartPlus,
    CartShopping,
    CashRegister,
    Cat,
    CediSign,
    CentSign,
    Certificate,
    Chair,
    Chalkboard,
    ChalkboardUser,
    ChampagneGlasses,
    ChargingStation,
    ChartArea,
    ChartBar,
    ChartColumn,
    ChartDiagram,
    ChartGantt,
    ChartLine,
    ChartPie,
    ChartSimple,
    Check,
    CheckDouble,
    CheckToSlot,
    Cheese,
    Chess,
    ChessBishop,
    ChessBoard,
    ChessKing,
    ChessKnight,
    ChessPawn,
    ChessQueen,
    ChessRook,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Child,
    ChildCombatant,
    ChildDress,
    ChildReaching,
    Children,
    Church,
    Circle,
    CircleArrowDown,
    CircleArrowLeft,
    CircleArrowRight,
    CircleArrowUp,
    CircleCheck,
    CircleChevronDown,
    CircleChevronLeft,
    CircleChevronRight,
    CircleChevronUp,
    CircleDollarToSlot,
    CircleDot,
    CircleDown,
    CircleExclamation,
    CircleH,
    CircleHalfStroke,
    CircleInfo,
    CircleLeft,
    CircleMinus,
    CircleNodes,
    CircleNotch,
    CirclePause,
    CirclePlay,
    CirclePlus,
    CircleQuestion,
    CircleRadiation,
    CircleRight,
    CircleStop,
    CircleUp,
    CircleUser,
    CircleXmark,
    City,
    Clapperboard,
    Clipboard,
    ClipboardCheck,
    ClipboardList,
    ClipboardQuestion,
    ClipboardUser,
    Clock,
    ClockRotateLeft,
    Clone,
    ClosedCaptioning,
    Cloud,
    CloudArrowDown,
    CloudArrowUp,
    CloudBolt,
    CloudMeatball,
    CloudMoon,
    CloudMoonRain,
    CloudRain,
    CloudShowersHeavy,
    CloudShowersWater,
    CloudSun,
    CloudSunRain,
    Clover,
    Code,
    CodeBranch,
    CodeCommit,
    CodeCompare,
    CodeFork,
    CodeMerge,
    CodePullRequest,
    Coins,
    ColonSign,
    Comment,
    CommentDollar,
    CommentDots,
    CommentMedical,
    CommentNodes,
    CommentSlash,
    CommentSms,
    Comments,
    CommentsDollar,
    CompactDisc,
    Compass,
    CompassDrafting,
    Compress,
    Computer,
    ComputerMouse,
    Cookie,
    CookieBite,
    Copy,
    Copyright,
    Couch,
    Cow,
    CreditCard,
    Crop,
    CropSimple,
    Cross,
    Crosshairs,
    Crow,
    Crown,
    Crutch,
    CruzeiroSign,
    Cube,
    Cubes,
    CubesStacked,
    D,
    Database,
    DeleteLeft,
    Democrat,
    Desktop,
    Dharmachakra,
    DiagramNext,
    DiagramPredecessor,
    DiagramProject,
    DiagramSuccessor,
    Diamond,
    DiamondTurnRight,
    Dice,
    DiceD20,
    DiceD6,
    DiceFive,
    DiceFour,
    DiceOne,
    DiceSix,
    DiceThree,
    DiceTwo,
    Disease,
    Display,
    Divide,
    Dna,
    Dog,
    DollarSign,
    Dolly,
    DongSign,
    DoorClosed,
    DoorOpen,
    Dove,
    DownLeftAndUpRightToCenter,
    DownLong,
    Download,
    Dragon,
    DrawPolygon,
    Droplet,
    DropletSlash,
    Drum,
    DrumSteelpan,
    DrumstickBite,
    Dumbbell,
    Dumpster,
    DumpsterFire,
    Dungeon,
    E,
    EarDeaf,
    EarListen,
    EarthAfrica,
    EarthAmericas,
    EarthAsia,
    EarthEurope,
    EarthOceania,
    Egg,
    Eject,
    Elevator,
    Ellipsis,
    EllipsisVertical,
    Envelope,
    EnvelopeCircleCheck,
    EnvelopeOpen,
    EnvelopeOpenText,
    EnvelopesBulk,
    Equals,
    Eraser,
    Ethernet,
    EuroSign,
    Exclamation,
    Expand,
    Explosion,
    Eye,
    EyeDropper,
    EyeLowVision,
    EyeSlash,
    F,
    FaceAngry,
    FaceDizzy,
    FaceFlushed,
    FaceFrown,
    FaceFrownOpen,
    FaceGrimace,
    FaceGrin,
    FaceGrinBeam,
    FaceGrinBeamSweat,
    FaceGrinHearts,
    FaceGrinSquint,
    FaceGrinSquintTears,
    FaceGrinStars,
    FaceGrinTears,
    FaceGrinTongue,
    FaceGrinTongueSquint,
    FaceGrinTongueWink,
    FaceGrinWide,
    FaceGrinWink,
    FaceKiss,
    FaceKissBeam,
    FaceKissWinkHeart,
    FaceLaugh,
    FaceLaughBeam,
    FaceLaughSquint,
    FaceLaughWink,
    FaceMeh,
    FaceMehBlank,
    FaceRollingEyes,
    FaceSadCry,
    FaceSadTear,
    FaceSmile,
    FaceSmileBeam,
    FaceSmileWink,
    FaceSurprise,
    FaceTired,
    Fan,
    Faucet,
    FaucetDrip,
    Fax,
    Feather,
    FeatherPointed,
    Ferry,
    File,
    FileArrowDown,
    FileArrowUp,
    FileAudio,
    FileCircleCheck,
    FileCircleExclamation,
    FileCircleMinus,
    FileCirclePlus,
    FileCircleQuestion,
    FileCircleXmark,
    FileCode,
    FileContract,
    FileCsv,
    FileExcel,
    FileExport,
    FileFragment,
    FileHalfDashed,
    FileImage,
    FileImport,
    FileInvoice,
    FileInvoiceDollar,
    FileLines,
    FileMedical,
    FilePdf,
    FilePen,
    FilePowerpoint,
    FilePrescription,
    FileShield,
    FileSignature,
    FileVideo,
    FileWaveform,
    FileWord,
    FileZipper,
    Fill,
    FillDrip,
    Film,
    Filter,
    FilterCircleDollar,
    FilterCircleXmark,
    Fingerprint,
    Fire,
    FireBurner,
    FireExtinguisher,
    FireFlameCurved,
    FireFlameSimple,
    Fish,
    FishFins,
    Flag,
    FlagCheckered,
    FlagUsa,
    Flask,
    FlaskVial,
    FloppyDisk,
    FlorinSign,
    Folder,
    FolderClosed,
    FolderMinus,
    FolderOpen,
    FolderPlus,
    FolderTree,
    Font,
    FontAwesome,
    Football,
    Forward,
    ForwardFast,
    ForwardStep,
    FrancSign,
    Frog,
    Futbol,
    G,
    Gamepad,
    GasPump,
    Gauge,
    GaugeHigh,
    GaugeSimple,
    GaugeSimpleHigh,
    Gavel,
    Gear,
    Gears,
    Gem,
    Genderless,
    Ghost,
    Gift,
    Gifts,
    GlassWater,
    GlassWaterDroplet,
    Glasses,
    Globe,
    GolfBallTee,
    Gopuram,
    GraduationCap,
    GreaterThan,
    GreaterThanEqual,
    Grip,
    GripLines,
    GripLinesVertical,
    GripVertical,
    GroupArrowsRotate,
    GuaraniSign,
    Guitar,
    Gun,
    H,
    Hammer,
    Hamsa,
    Hand,
    HandBackFist,
    HandDots,
    HandFist,
    HandHolding,
    HandHoldingDollar,
    HandHoldingDroplet,
    HandHoldingHand,
    HandHoldingHeart,
    HandHoldingMedical,
    HandLizard,
    HandMiddleFinger,
    HandPeace,
    HandPointDown,
    HandPointLeft,
    HandPointRight,
    HandPointUp,
    HandPointer,
    HandScissors,
    HandSparkles,
    HandSpock,
    Handcuffs,
    Hands,
    HandsAslInterpreting,
    HandsBound,
    HandsBubbles,
    HandsClapping,
    HandsHolding,
    HandsHoldingChild,
    HandsHoldingCircle,
    HandsPraying,
    Handshake,
    HandshakeAngle,
    HandshakeSimple,
    HandshakeSimpleSlash,
    HandshakeSlash,
    Hanukiah,
    HardDrive,
    Hashtag,
    HatCowboy,
    HatCowboySide,
    HatWizard,
    HeadSideCough,
    HeadSideCoughSlash,
    HeadSideMask,
    HeadSideVirus,
    Heading,
    Headphones,
    HeadphonesSimple,
    Headset,
    Heart,
    HeartCircleBolt,
    HeartCircleCheck,
    HeartCircleExclamation,
    HeartCircleMinus,
    HeartCirclePlus,
    HeartCircleXmark,
    HeartCrack,
    HeartPulse,
    Helicopter,
    HelicopterSymbol,
    HelmetSafety,
    HelmetUn,
    HexagonNodes,
    HexagonNodesBolt,
    Highlighter,
    HillAvalanche,
    HillRockslide,
    Hippo,
    HockeyPuck,
    HollyBerry,
    Horse,
    HorseHead,
    Hospital,
    HospitalUser,
    HotTubPerson,
    Hotdog,
    Hotel,
    Hourglass,
    HourglassEnd,
    HourglassHalf,
    HourglassStart,
    House,
    HouseChimney,
    HouseChimneyCrack,
    HouseChimneyMedical,
    HouseChimneyUser,
    HouseChimneyWindow,
    HouseCircleCheck,
    HouseCircleExclamation,
    HouseCircleXmark,
    HouseCrack,
    HouseFire,
    HouseFlag,
    HouseFloodWater,
    HouseFloodWaterCircleArrowRight,
    HouseLaptop,
    HouseLock,
    HouseMedical,
    HouseMedicalCircleCheck,
    HouseMedicalCircleExclamation,
    HouseMedicalCircleXmark,
    HouseMedicalFlag,
    HouseSignal,
    HouseTsunami,
    HouseUser,
    HryvniaSign,
    Hurricane,
    I,
    ICursor,
    IceCream,
    Icicles,
    Icons,
    IdBadge,
    IdCard,
    IdCardClip,
    Igloo,
    Image,
    ImagePortrait,
    Images,
    Inbox,
    Indent,
    IndianRupeeSign,
    Industry,
    Infinity,
    Info,
    Italic,
    J,
    Jar,
    JarWheat,
    Jedi,
    JetFighter,
    JetFighterUp,
    Joint,
    JugDetergent,
    K,
    Kaaba,
    Key,
    Keyboard,
    Khanda,
    KipSign,
    KitMedical,
    KitchenSet,
    KiwiBird,
    L,
    LandMineOn,
    Landmark,
    LandmarkDome,
    LandmarkFlag,
    Language,
    Laptop,
    LaptopCode,
    LaptopFile,
    LaptopMedical,
    LariSign,
    LayerGroup,
    Leaf,
    LeftLong,
    LeftRight,
    Lemon,
    LessThan,
    LessThanEqual,
    LifeRing,
    Lightbulb,
    LinesLeaning,
    Link,
    LinkSlash,
    LiraSign,
    List,
    ListCheck,
    ListOl,
    ListUl,
    LitecoinSign,
    LocationArrow,
    LocationCrosshairs,
    LocationDot,
    LocationPin,
    LocationPinLock,
    Lock,
    LockOpen,
    Locust,
    Lungs,
    LungsVirus,
    M,
    Magnet,
    MagnifyingGlass,
    MagnifyingGlassArrowRight,
    MagnifyingGlassChart,
    MagnifyingGlassDollar,
    MagnifyingGlassLocation,
    MagnifyingGlassMinus,
    MagnifyingGlassPlus,
    ManatSign,
    Map,
    MapLocation,
    MapLocationDot,
    MapPin,
    Marker,
    Mars,
    MarsAndVenus,
    MarsAndVenusBurst,
    MarsDouble,
    MarsStroke,
    MarsStrokeRight,
    MarsStrokeUp,
    MartiniGlass,
    MartiniGlassCitrus,
    MartiniGlassEmpty,
    Mask,
    MaskFace,
    MaskVentilator,
    MasksTheater,
    MattressPillow,
    Maximize,
    Medal,
    Memory,
    Menorah,
    Mercury,
    Message,
    Meteor,
    Microchip,
    Microphone,
    MicrophoneLines,
    MicrophoneLinesSlash,
    MicrophoneSlash,
    Microscope,
    MillSign,
    Minimize,
    Minus,
    Mitten,
    Mobile,
    MobileButton,
    MobileRetro,
    MobileScreen,
    MobileScreenButton,
    MoneyBill,
    MoneyBill1,
    MoneyBill1Wave,
    MoneyBillTransfer,
    MoneyBillTrendUp,
    MoneyBillWave,
    MoneyBillWheat,
    MoneyBills,
    MoneyCheck,
    MoneyCheckDollar,
    Monument,
    Moon,
    MortarPestle,
    Mosque,
    Mosquito,
    MosquitoNet,
    Motorcycle,
    Mound,
    Mountain,
    MountainCity,
    MountainSun,
    MugHot,
    MugSaucer,
    Music,
    N,
    NairaSign,
    NetworkWired,
    Neuter,
    Newspaper,
    NotEqual,
    Notdef,
    NoteSticky,
    NotesMedical,
    O,
    ObjectGroup,
    ObjectUngroup,
    OilCan,
    OilWell,
    Om,
    Otter,
    Outdent,
    P,
    Pager,
    PaintRoller,
    Paintbrush,
    Palette,
    Pallet,
    Panorama,
    PaperPlane,
    Paperclip,
    ParachuteBox,
    Paragraph,
    Passport,
    Paste,
    Pause,
    Paw,
    Peace,
    Pen,
    PenClip,
    PenFancy,
    PenNib,
    PenRuler,
    PenToSquare,
    Pencil,
    PeopleArrows,
    PeopleCarryBox,
    PeopleGroup,
    PeopleLine,
    PeoplePulling,
    PeopleRobbery,
    PeopleRoof,
    PepperHot,
    Percent,
    Person,
    PersonArrowDownToLine,
    PersonArrowUpFromLine,
    PersonBiking,
    PersonBooth,
    PersonBreastfeeding,
    PersonBurst,
    PersonCane,
    PersonChalkboard,
    PersonCircleCheck,
    PersonCircleExclamation,
    PersonCircleMinus,
    PersonCirclePlus,
    PersonCircleQuestion,
    PersonCircleXmark,
    PersonDigging,
    PersonDotsFromLine,
    PersonDress,
    PersonDressBurst,
    PersonDrowning,
    PersonFalling,
    PersonFallingBurst,
    PersonHalfDress,
    PersonHarassing,
    PersonHiking,
    PersonMilitaryPointing,
    PersonMilitaryRifle,
    PersonMilitaryToPerson,
    PersonPraying,
    PersonPregnant,
    PersonRays,
    PersonRifle,
    PersonRunning,
    PersonShelter,
    PersonSkating,
    PersonSkiing,
    PersonSkiingNordic,
    PersonSnowboarding,
    PersonSwimming,
    PersonThroughWindow,
    PersonWalking,
    PersonWalkingArrowLoopLeft,
    PersonWalkingArrowRight,
    PersonWalkingDashedLineArrowRight,
    PersonWalkingLuggage,
    PersonWalkingWithCane,
    PesetaSign,
    PesoSign,
    Phone,
    PhoneFlip,
    PhoneSlash,
    PhoneVolume,
    PhotoFilm,
    PiggyBank,
    Pills,
    PizzaSlice,
    PlaceOfWorship,
    Plane,
    PlaneArrival,
    PlaneCircleCheck,
    PlaneCircleExclamation,
    PlaneCircleXmark,
    PlaneDeparture,
    PlaneLock,
    PlaneSlash,
    PlaneUp,
    PlantWilt,
    PlateWheat,
    Play,
    Plug,
    PlugCircleBolt,
    PlugCircleCheck,
    PlugCircleExclamation,
    PlugCircleMinus,
    PlugCirclePlus,
    PlugCircleXmark,
    Plus,
    PlusMinus,
    Podcast,
    Poo,
    PooStorm,
    Poop,
    PowerOff,
    Prescription,
    PrescriptionBottle,
    PrescriptionBottleMedical,
    Print,
    PumpMedical,
    PumpSoap,
    PuzzlePiece,
    Q,
    Qrcode,
    Question,
    QuoteLeft,
    QuoteRight,
    R,
    Radiation,
    Radio,
    Rainbow,
    RankingStar,
    Receipt,
    RecordVinyl,
    RectangleAd,
    RectangleList,
    RectangleXmark,
    Recycle,
    Registered,
    Repeat,
    Reply,
    ReplyAll,
    Republican,
    Restroom,
    Retweet,
    Ribbon,
    RightFromBracket,
    RightLeft,
    RightLong,
    RightToBracket,
    Ring,
    Road,
    RoadBarrier,
    RoadBridge,
    RoadCircleCheck,
    RoadCircleExclamation,
    RoadCircleXmark,
    RoadLock,
    RoadSpikes,
    Robot,
    Rocket,
    Rotate,
    RotateLeft,
    RotateRight,
    Route,
    Rss,
    RubleSign,
    Rug,
    Ruler,
    RulerCombined,
    RulerHorizontal,
    RulerVertical,
    RupeeSign,
    RupiahSign,
    S,
    SackDollar,
    SackXmark,
    Sailboat,
    Satellite,
    SatelliteDish,
    ScaleBalanced,
    ScaleUnbalanced,
    ScaleUnbalancedFlip,
    School,
    SchoolCircleCheck,
    SchoolCircleExclamation,
    SchoolCircleXmark,
    SchoolFlag,
    SchoolLock,
    Scissors,
    Screwdriver,
    ScrewdriverWrench,
    Scroll,
    ScrollTorah,
    SdCard,
    Section,
    Seedling,
    Server,
    Shapes,
    Share,
    ShareFromSquare,
    ShareNodes,
    SheetPlastic,
    ShekelSign,
    Shield,
    ShieldCat,
    ShieldDog,
    ShieldHalved,
    ShieldHeart,
    ShieldVirus,
    Ship,
    Shirt,
    ShoePrints,
    Shop,
    ShopLock,
    ShopSlash,
    Shower,
    Shrimp,
    Shuffle,
    ShuttleSpace,
    SignHanging,
    Signal,
    Signature,
    SignsPost,
    SimCard,
    Sink,
    Sitemap,
    Skull,
    SkullCrossbones,
    Slash,
    Sleigh,
    Sliders,
    Smog,
    Smoking,
    Snowflake,
    Snowman,
    Snowplow,
    Soap,
    Socks,
    SolarPanel,
    Sort,
    SortDown,
    SortUp,
    Spa,
    SpaghettiMonsterFlying,
    SpellCheck,
    Spider,
    Spinner,
    Splotch,
    Spoon,
    SprayCan,
    SprayCanSparkles,
    Square,
    SquareArrowUpRight,
    SquareBinary,
    SquareCaretDown,
    SquareCaretLeft,
    SquareCaretRight,
    SquareCaretUp,
    SquareCheck,
    SquareEnvelope,
    SquareFull,
    SquareH,
    SquareMinus,
    SquareNfi,
    SquareParking,
    SquarePen,
    SquarePersonConfined,
    SquarePhone,
    SquarePhoneFlip,
    SquarePlus,
    SquarePollHorizontal,
    SquarePollVertical,
    SquareRootVariable,
    SquareRss,
    SquareShareNodes,
    SquareUpRight,
    SquareVirus,
    SquareXmark,
    StaffSnake,
    Stairs,
    Stamp,
    Stapler,
    Star,
    StarAndCrescent,
    StarHalf,
    StarHalfStroke,
    StarOfDavid,
    StarOfLife,
    SterlingSign,
    Stethoscope,
    Stop,
    Stopwatch,
    Stopwatch20,
    Store,
    StoreSlash,
    StreetView,
    Strikethrough,
    Stroopwafel,
    Subscript,
    Suitcase,
    SuitcaseMedical,
    SuitcaseRolling,
    Sun,
    SunPlantWilt,
    Superscript,
    Swatchbook,
    Synagogue,
    Syringe,
    T,
    Table,
    TableCells,
    TableCellsColumnLock,
    TableCellsLarge,
    TableCellsRowLock,
    TableCellsRowUnlock,
    TableColumns,
    TableList,
    TableTennisPaddleBall,
    Tablet,
    TabletButton,
    TabletScreenButton,
    Tablets,
    TachographDigital,
    Tag,
    Tags,
    Tape,
    Tarp,
    TarpDroplet,
    Taxi,
    Teeth,
    TeethOpen,
    TemperatureArrowDown,
    TemperatureArrowUp,
    TemperatureEmpty,
    TemperatureFull,
    TemperatureHalf,
    TemperatureHigh,
    TemperatureLow,
    TemperatureQuarter,
    TemperatureThreeQuarters,
    TengeSign,
    Tent,
    TentArrowDownToLine,
    TentArrowLeftRight,
    TentArrowTurnLeft,
    TentArrowsDown,
    Tents,
    Terminal,
    TextHeight,
    TextSlash,
    TextWidth,
    Thermometer,
    ThumbsDown,
    ThumbsUp,
    Thumbtack,
    ThumbtackSlash,
    Ticket,
    TicketSimple,
    Timeline,
    ToggleOff,
    ToggleOn,
    Toilet,
    ToiletPaper,
    ToiletPaperSlash,
    ToiletPortable,
    ToiletsPortable,
    Toolbox,
    Tooth,
    ToriiGate,
    Tornado,
    TowerBroadcast,
    TowerCell,
    TowerObservation,
    Tractor,
    Trademark,
    TrafficLight,
    Trailer,
    Train,
    TrainSubway,
    TrainTram,
    Transgender,
    Trash,
    TrashArrowUp,
    TrashCan,
    TrashCanArrowUp,
    Tree,
    TreeCity,
    TriangleExclamation,
    Trophy,
    Trowel,
    TrowelBricks,
    Truck,
    TruckArrowRight,
    TruckDroplet,
    TruckFast,
    TruckField,
    TruckFieldUn,
    TruckFront,
    TruckMedical,
    TruckMonster,
    TruckMoving,
    TruckPickup,
    TruckPlane,
    TruckRampBox,
    Tty,
    TurkishLiraSign,
    TurnDown,
    TurnUp,
    Tv,
    U,
    Umbrella,
    UmbrellaBeach,
    Underline,
    UniversalAccess,
    Unlock,
    UnlockKeyhole,
    UpDown,
    UpDownLeftRight,
    UpLong,
    UpRightAndDownLeftFromCenter,
    UpRightFromSquare,
    Upload,
    User,
    UserAstronaut,
    UserCheck,
    UserClock,
    UserDoctor,
    UserGear,
    UserGraduate,
    UserGroup,
    UserInjured,
    UserLarge,
    UserLargeSlash,
    UserLock,
    UserMinus,
    UserNinja,
    UserNurse,
    UserPen,
    UserPlus,
    UserSecret,
    UserShield,
    UserSlash,
    UserTag,
    UserTie,
    UserXmark,
    Users,
    UsersBetweenLines,
    UsersGear,
    UsersLine,
    UsersRays,
    UsersRectangle,
    UsersSlash,
    UsersViewfinder,
    Utensils,
    V,
    VanShuttle,
    Vault,
    VectorSquare,
    Venus,
    VenusDouble,
    VenusMars,
    Vest,
    VestPatches,
    Vial,
    VialCircleCheck,
    VialVirus,
    Vials,
    Video,
    VideoSlash,
    Vihara,
    Virus,
    VirusCovid,
    VirusCovidSlash,
    VirusSlash,
    Viruses,
    Voicemail,
    Volcano,
    Volleyball,
    VolumeHigh,
    VolumeLow,
    VolumeOff,
    VolumeXmark,
    VrCardboard,
    W,
    WalkieTalkie,
    Wallet,
    WandMagic,
    WandMagicSparkles,
    WandSparkles,
    Warehouse,
    Water,
    WaterLadder,
    WaveSquare,
    WebAwesome,
    WeightHanging,
    WeightScale,
    WheatAwn,
    WheatAwnCircleExclamation,
    Wheelchair,
    WheelchairMove,
    WhiskeyGlass,
    Wifi,
    Wind,
    WindowMaximize,
    WindowMinimize,
    WindowRestore,
    WineBottle,
    WineGlass,
    WineGlassEmpty,
    WonSign,
    Worm,
    Wrench,
    X,
    XRay,
    Xmark,
    XmarksLines,
    Y,
    YenSign,
    YinYang,
    Z,
}

impl FontAwesomeSolid {
    pub fn to_string(&self) -> &str {
        match self {
            Self::A => "\u{41}",
            Self::AddressBook => "\u{f2b9}",
            Self::AddressCard => "\u{f2bb}",
            Self::AlignCenter => "\u{f037}",
            Self::AlignJustify => "\u{f039}",
            Self::AlignLeft => "\u{f036}",
            Self::AlignRight => "\u{f038}",
            Self::Anchor => "\u{f13d}",
            Self::AnchorCircleCheck => "\u{e4aa}",
            Self::AnchorCircleExclamation => "\u{e4ab}",
            Self::AnchorCircleXmark => "\u{e4ac}",
            Self::AnchorLock => "\u{e4ad}",
            Self::AngleDown => "\u{f107}",
            Self::AngleLeft => "\u{f104}",
            Self::AngleRight => "\u{f105}",
            Self::AngleUp => "\u{f106}",
            Self::AnglesDown => "\u{f103}",
            Self::AnglesLeft => "\u{f100}",
            Self::AnglesRight => "\u{f101}",
            Self::AnglesUp => "\u{f102}",
            Self::Ankh => "\u{f644}",
            Self::AppleWhole => "\u{f5d1}",
            Self::Archway => "\u{f557}",
            Self::ArrowDown => "\u{f063}",
            Self::ArrowDown19 => "\u{f162}",
            Self::ArrowDown91 => "\u{f886}",
            Self::ArrowDownAZ => "\u{f15d}",
            Self::ArrowDownLong => "\u{f175}",
            Self::ArrowDownShortWide => "\u{f884}",
            Self::ArrowDownUpAcrossLine => "\u{e4af}",
            Self::ArrowDownUpLock => "\u{e4b0}",
            Self::ArrowDownWideShort => "\u{f160}",
            Self::ArrowDownZA => "\u{f881}",
            Self::ArrowLeft => "\u{f060}",
            Self::ArrowLeftLong => "\u{f177}",
            Self::ArrowPointer => "\u{f245}",
            Self::ArrowRight => "\u{f061}",
            Self::ArrowRightArrowLeft => "\u{f0ec}",
            Self::ArrowRightFromBracket => "\u{f08b}",
            Self::ArrowRightLong => "\u{f178}",
            Self::ArrowRightToBracket => "\u{f090}",
            Self::ArrowRightToCity => "\u{e4b3}",
            Self::ArrowRotateLeft => "\u{f0e2}",
            Self::ArrowRotateRight => "\u{f01e}",
            Self::ArrowTrendDown => "\u{e097}",
            Self::ArrowTrendUp => "\u{e098}",
            Self::ArrowTurnDown => "\u{f149}",
            Self::ArrowTurnUp => "\u{f148}",
            Self::ArrowUp => "\u{f062}",
            Self::ArrowUp19 => "\u{f163}",
            Self::ArrowUp91 => "\u{f887}",
            Self::ArrowUpAZ => "\u{f15e}",
            Self::ArrowUpFromBracket => "\u{e09a}",
            Self::ArrowUpFromGroundWater => "\u{e4b5}",
            Self::ArrowUpFromWaterPump => "\u{e4b6}",
            Self::ArrowUpLong => "\u{f176}",
            Self::ArrowUpRightDots => "\u{e4b7}",
            Self::ArrowUpRightFromSquare => "\u{f08e}",
            Self::ArrowUpShortWide => "\u{f885}",
            Self::ArrowUpWideShort => "\u{f161}",
            Self::ArrowUpZA => "\u{f882}",
            Self::ArrowsDownToLine => "\u{e4b8}",
            Self::ArrowsDownToPeople => "\u{e4b9}",
            Self::ArrowsLeftRight => "\u{f07e}",
            Self::ArrowsLeftRightToLine => "\u{e4ba}",
            Self::ArrowsRotate => "\u{f021}",
            Self::ArrowsSpin => "\u{e4bb}",
            Self::ArrowsSplitUpAndLeft => "\u{e4bc}",
            Self::ArrowsToCircle => "\u{e4bd}",
            Self::ArrowsToDot => "\u{e4be}",
            Self::ArrowsToEye => "\u{e4bf}",
            Self::ArrowsTurnRight => "\u{e4c0}",
            Self::ArrowsTurnToDots => "\u{e4c1}",
            Self::ArrowsUpDown => "\u{f07d}",
            Self::ArrowsUpDownLeftRight => "\u{f047}",
            Self::ArrowsUpToLine => "\u{e4c2}",
            Self::Asterisk => "\u{2a}",
            Self::At => "\u{40}",
            Self::Atom => "\u{f5d2}",
            Self::AudioDescription => "\u{f29e}",
            Self::AustralSign => "\u{e0a9}",
            Self::Award => "\u{f559}",
            Self::B => "\u{42}",
            Self::Baby => "\u{f77c}",
            Self::BabyCarriage => "\u{f77d}",
            Self::Backward => "\u{f04a}",
            Self::BackwardFast => "\u{f049}",
            Self::BackwardStep => "\u{f048}",
            Self::Bacon => "\u{f7e5}",
            Self::Bacteria => "\u{e059}",
            Self::Bacterium => "\u{e05a}",
            Self::BagShopping => "\u{f290}",
            Self::Bahai => "\u{f666}",
            Self::BahtSign => "\u{e0ac}",
            Self::Ban => "\u{f05e}",
            Self::BanSmoking => "\u{f54d}",
            Self::Bandage => "\u{f462}",
            Self::BangladeshiTakaSign => "\u{e2e6}",
            Self::Barcode => "\u{f02a}",
            Self::Bars => "\u{f0c9}",
            Self::BarsProgress => "\u{f828}",
            Self::BarsStaggered => "\u{f550}",
            Self::Baseball => "\u{f433}",
            Self::BaseballBatBall => "\u{f432}",
            Self::BasketShopping => "\u{f291}",
            Self::Basketball => "\u{f434}",
            Self::Bath => "\u{f2cd}",
            Self::BatteryEmpty => "\u{f244}",
            Self::BatteryFull => "\u{f240}",
            Self::BatteryHalf => "\u{f242}",
            Self::BatteryQuarter => "\u{f243}",
            Self::BatteryThreeQuarters => "\u{f241}",
            Self::Bed => "\u{f236}",
            Self::BedPulse => "\u{f487}",
            Self::BeerMugEmpty => "\u{f0fc}",
            Self::Bell => "\u{f0f3}",
            Self::BellConcierge => "\u{f562}",
            Self::BellSlash => "\u{f1f6}",
            Self::BezierCurve => "\u{f55b}",
            Self::Bicycle => "\u{f206}",
            Self::Binoculars => "\u{f1e5}",
            Self::Biohazard => "\u{f780}",
            Self::BitcoinSign => "\u{e0b4}",
            Self::Blender => "\u{f517}",
            Self::BlenderPhone => "\u{f6b6}",
            Self::Blog => "\u{f781}",
            Self::Bold => "\u{f032}",
            Self::Bolt => "\u{f0e7}",
            Self::BoltLightning => "\u{e0b7}",
            Self::Bomb => "\u{f1e2}",
            Self::Bone => "\u{f5d7}",
            Self::Bong => "\u{f55c}",
            Self::Book => "\u{f02d}",
            Self::BookAtlas => "\u{f558}",
            Self::BookBible => "\u{f647}",
            Self::BookBookmark => "\u{e0bb}",
            Self::BookJournalWhills => "\u{f66a}",
            Self::BookMedical => "\u{f7e6}",
            Self::BookOpen => "\u{f518}",
            Self::BookOpenReader => "\u{f5da}",
            Self::BookQuran => "\u{f687}",
            Self::BookSkull => "\u{f6b7}",
            Self::BookTanakh => "\u{f827}",
            Self::Bookmark => "\u{f02e}",
            Self::BorderAll => "\u{f84c}",
            Self::BorderNone => "\u{f850}",
            Self::BorderTopLeft => "\u{f853}",
            Self::BoreHole => "\u{e4c3}",
            Self::BottleDroplet => "\u{e4c4}",
            Self::BottleWater => "\u{e4c5}",
            Self::BowlFood => "\u{e4c6}",
            Self::BowlRice => "\u{e2eb}",
            Self::BowlingBall => "\u{f436}",
            Self::Box => "\u{f466}",
            Self::BoxArchive => "\u{f187}",
            Self::BoxOpen => "\u{f49e}",
            Self::BoxTissue => "\u{e05b}",
            Self::BoxesPacking => "\u{e4c7}",
            Self::BoxesStacked => "\u{f468}",
            Self::Braille => "\u{f2a1}",
            Self::Brain => "\u{f5dc}",
            Self::BrazilianRealSign => "\u{e46c}",
            Self::BreadSlice => "\u{f7ec}",
            Self::Bridge => "\u{e4c8}",
            Self::BridgeCircleCheck => "\u{e4c9}",
            Self::BridgeCircleExclamation => "\u{e4ca}",
            Self::BridgeCircleXmark => "\u{e4cb}",
            Self::BridgeLock => "\u{e4cc}",
            Self::BridgeWater => "\u{e4ce}",
            Self::Briefcase => "\u{f0b1}",
            Self::BriefcaseMedical => "\u{f469}",
            Self::Broom => "\u{f51a}",
            Self::BroomBall => "\u{f458}",
            Self::Brush => "\u{f55d}",
            Self::Bucket => "\u{e4cf}",
            Self::Bug => "\u{f188}",
            Self::BugSlash => "\u{e490}",
            Self::Bugs => "\u{e4d0}",
            Self::Building => "\u{f1ad}",
            Self::BuildingCircleArrowRight => "\u{e4d1}",
            Self::BuildingCircleCheck => "\u{e4d2}",
            Self::BuildingCircleExclamation => "\u{e4d3}",
            Self::BuildingCircleXmark => "\u{e4d4}",
            Self::BuildingColumns => "\u{f19c}",
            Self::BuildingFlag => "\u{e4d5}",
            Self::BuildingLock => "\u{e4d6}",
            Self::BuildingNgo => "\u{e4d7}",
            Self::BuildingShield => "\u{e4d8}",
            Self::BuildingUn => "\u{e4d9}",
            Self::BuildingUser => "\u{e4da}",
            Self::BuildingWheat => "\u{e4db}",
            Self::Bullhorn => "\u{f0a1}",
            Self::Bullseye => "\u{f140}",
            Self::Burger => "\u{f805}",
            Self::Burst => "\u{e4dc}",
            Self::Bus => "\u{f207}",
            Self::BusSimple => "\u{f55e}",
            Self::BusinessTime => "\u{f64a}",
            Self::C => "\u{43}",
            Self::CableCar => "\u{f7da}",
            Self::CakeCandles => "\u{f1fd}",
            Self::Calculator => "\u{f1ec}",
            Self::Calendar => "\u{f133}",
            Self::CalendarCheck => "\u{f274}",
            Self::CalendarDay => "\u{f783}",
            Self::CalendarDays => "\u{f073}",
            Self::CalendarMinus => "\u{f272}",
            Self::CalendarPlus => "\u{f271}",
            Self::CalendarWeek => "\u{f784}",
            Self::CalendarXmark => "\u{f273}",
            Self::Camera => "\u{f030}",
            Self::CameraRetro => "\u{f083}",
            Self::CameraRotate => "\u{e0d8}",
            Self::Campground => "\u{f6bb}",
            Self::CandyCane => "\u{f786}",
            Self::Cannabis => "\u{f55f}",
            Self::Capsules => "\u{f46b}",
            Self::Car => "\u{f1b9}",
            Self::CarBattery => "\u{f5df}",
            Self::CarBurst => "\u{f5e1}",
            Self::CarOn => "\u{e4dd}",
            Self::CarRear => "\u{f5de}",
            Self::CarSide => "\u{f5e4}",
            Self::CarTunnel => "\u{e4de}",
            Self::Caravan => "\u{f8ff}",
            Self::CaretDown => "\u{f0d7}",
            Self::CaretLeft => "\u{f0d9}",
            Self::CaretRight => "\u{f0da}",
            Self::CaretUp => "\u{f0d8}",
            Self::Carrot => "\u{f787}",
            Self::CartArrowDown => "\u{f218}",
            Self::CartFlatbed => "\u{f474}",
            Self::CartFlatbedSuitcase => "\u{f59d}",
            Self::CartPlus => "\u{f217}",
            Self::CartShopping => "\u{f07a}",
            Self::CashRegister => "\u{f788}",
            Self::Cat => "\u{f6be}",
            Self::CediSign => "\u{e0df}",
            Self::CentSign => "\u{e3f5}",
            Self::Certificate => "\u{f0a3}",
            Self::Chair => "\u{f6c0}",
            Self::Chalkboard => "\u{f51b}",
            Self::ChalkboardUser => "\u{f51c}",
            Self::ChampagneGlasses => "\u{f79f}",
            Self::ChargingStation => "\u{f5e7}",
            Self::ChartArea => "\u{f1fe}",
            Self::ChartBar => "\u{f080}",
            Self::ChartColumn => "\u{e0e3}",
            Self::ChartDiagram => "\u{e695}",
            Self::ChartGantt => "\u{e0e4}",
            Self::ChartLine => "\u{f201}",
            Self::ChartPie => "\u{f200}",
            Self::ChartSimple => "\u{e473}",
            Self::Check => "\u{f00c}",
            Self::CheckDouble => "\u{f560}",
            Self::CheckToSlot => "\u{f772}",
            Self::Cheese => "\u{f7ef}",
            Self::Chess => "\u{f439}",
            Self::ChessBishop => "\u{f43a}",
            Self::ChessBoard => "\u{f43c}",
            Self::ChessKing => "\u{f43f}",
            Self::ChessKnight => "\u{f441}",
            Self::ChessPawn => "\u{f443}",
            Self::ChessQueen => "\u{f445}",
            Self::ChessRook => "\u{f447}",
            Self::ChevronDown => "\u{f078}",
            Self::ChevronLeft => "\u{f053}",
            Self::ChevronRight => "\u{f054}",
            Self::ChevronUp => "\u{f077}",
            Self::Child => "\u{f1ae}",
            Self::ChildCombatant => "\u{e4e0}",
            Self::ChildDress => "\u{e59c}",
            Self::ChildReaching => "\u{e59d}",
            Self::Children => "\u{e4e1}",
            Self::Church => "\u{f51d}",
            Self::Circle => "\u{f111}",
            Self::CircleArrowDown => "\u{f0ab}",
            Self::CircleArrowLeft => "\u{f0a8}",
            Self::CircleArrowRight => "\u{f0a9}",
            Self::CircleArrowUp => "\u{f0aa}",
            Self::CircleCheck => "\u{f058}",
            Self::CircleChevronDown => "\u{f13a}",
            Self::CircleChevronLeft => "\u{f137}",
            Self::CircleChevronRight => "\u{f138}",
            Self::CircleChevronUp => "\u{f139}",
            Self::CircleDollarToSlot => "\u{f4b9}",
            Self::CircleDot => "\u{f192}",
            Self::CircleDown => "\u{f358}",
            Self::CircleExclamation => "\u{f06a}",
            Self::CircleH => "\u{f47e}",
            Self::CircleHalfStroke => "\u{f042}",
            Self::CircleInfo => "\u{f05a}",
            Self::CircleLeft => "\u{f359}",
            Self::CircleMinus => "\u{f056}",
            Self::CircleNodes => "\u{e4e2}",
            Self::CircleNotch => "\u{f1ce}",
            Self::CirclePause => "\u{f28b}",
            Self::CirclePlay => "\u{f144}",
            Self::CirclePlus => "\u{f055}",
            Self::CircleQuestion => "\u{f059}",
            Self::CircleRadiation => "\u{f7ba}",
            Self::CircleRight => "\u{f35a}",
            Self::CircleStop => "\u{f28d}",
            Self::CircleUp => "\u{f35b}",
            Self::CircleUser => "\u{f2bd}",
            Self::CircleXmark => "\u{f057}",
            Self::City => "\u{f64f}",
            Self::Clapperboard => "\u{e131}",
            Self::Clipboard => "\u{f328}",
            Self::ClipboardCheck => "\u{f46c}",
            Self::ClipboardList => "\u{f46d}",
            Self::ClipboardQuestion => "\u{e4e3}",
            Self::ClipboardUser => "\u{f7f3}",
            Self::Clock => "\u{f017}",
            Self::ClockRotateLeft => "\u{f1da}",
            Self::Clone => "\u{f24d}",
            Self::ClosedCaptioning => "\u{f20a}",
            Self::Cloud => "\u{f0c2}",
            Self::CloudArrowDown => "\u{f0ed}",
            Self::CloudArrowUp => "\u{f0ee}",
            Self::CloudBolt => "\u{f76c}",
            Self::CloudMeatball => "\u{f73b}",
            Self::CloudMoon => "\u{f6c3}",
            Self::CloudMoonRain => "\u{f73c}",
            Self::CloudRain => "\u{f73d}",
            Self::CloudShowersHeavy => "\u{f740}",
            Self::CloudShowersWater => "\u{e4e4}",
            Self::CloudSun => "\u{f6c4}",
            Self::CloudSunRain => "\u{f743}",
            Self::Clover => "\u{e139}",
            Self::Code => "\u{f121}",
            Self::CodeBranch => "\u{f126}",
            Self::CodeCommit => "\u{f386}",
            Self::CodeCompare => "\u{e13a}",
            Self::CodeFork => "\u{e13b}",
            Self::CodeMerge => "\u{f387}",
            Self::CodePullRequest => "\u{e13c}",
            Self::Coins => "\u{f51e}",
            Self::ColonSign => "\u{e140}",
            Self::Comment => "\u{f075}",
            Self::CommentDollar => "\u{f651}",
            Self::CommentDots => "\u{f4ad}",
            Self::CommentMedical => "\u{f7f5}",
            Self::CommentNodes => "\u{e696}",
            Self::CommentSlash => "\u{f4b3}",
            Self::CommentSms => "\u{f7cd}",
            Self::Comments => "\u{f086}",
            Self::CommentsDollar => "\u{f653}",
            Self::CompactDisc => "\u{f51f}",
            Self::Compass => "\u{f14e}",
            Self::CompassDrafting => "\u{f568}",
            Self::Compress => "\u{f066}",
            Self::Computer => "\u{e4e5}",
            Self::ComputerMouse => "\u{f8cc}",
            Self::Cookie => "\u{f563}",
            Self::CookieBite => "\u{f564}",
            Self::Copy => "\u{f0c5}",
            Self::Copyright => "\u{f1f9}",
            Self::Couch => "\u{f4b8}",
            Self::Cow => "\u{f6c8}",
            Self::CreditCard => "\u{f09d}",
            Self::Crop => "\u{f125}",
            Self::CropSimple => "\u{f565}",
            Self::Cross => "\u{f654}",
            Self::Crosshairs => "\u{f05b}",
            Self::Crow => "\u{f520}",
            Self::Crown => "\u{f521}",
            Self::Crutch => "\u{f7f7}",
            Self::CruzeiroSign => "\u{e152}",
            Self::Cube => "\u{f1b2}",
            Self::Cubes => "\u{f1b3}",
            Self::CubesStacked => "\u{e4e6}",
            Self::D => "\u{44}",
            Self::Database => "\u{f1c0}",
            Self::DeleteLeft => "\u{f55a}",
            Self::Democrat => "\u{f747}",
            Self::Desktop => "\u{f390}",
            Self::Dharmachakra => "\u{f655}",
            Self::DiagramNext => "\u{e476}",
            Self::DiagramPredecessor => "\u{e477}",
            Self::DiagramProject => "\u{f542}",
            Self::DiagramSuccessor => "\u{e47a}",
            Self::Diamond => "\u{f219}",
            Self::DiamondTurnRight => "\u{f5eb}",
            Self::Dice => "\u{f522}",
            Self::DiceD20 => "\u{f6cf}",
            Self::DiceD6 => "\u{f6d1}",
            Self::DiceFive => "\u{f523}",
            Self::DiceFour => "\u{f524}",
            Self::DiceOne => "\u{f525}",
            Self::DiceSix => "\u{f526}",
            Self::DiceThree => "\u{f527}",
            Self::DiceTwo => "\u{f528}",
            Self::Disease => "\u{f7fa}",
            Self::Display => "\u{e163}",
            Self::Divide => "\u{f529}",
            Self::Dna => "\u{f471}",
            Self::Dog => "\u{f6d3}",
            Self::DollarSign => "\u{24}",
            Self::Dolly => "\u{f472}",
            Self::DongSign => "\u{e169}",
            Self::DoorClosed => "\u{f52a}",
            Self::DoorOpen => "\u{f52b}",
            Self::Dove => "\u{f4ba}",
            Self::DownLeftAndUpRightToCenter => "\u{f422}",
            Self::DownLong => "\u{f309}",
            Self::Download => "\u{f019}",
            Self::Dragon => "\u{f6d5}",
            Self::DrawPolygon => "\u{f5ee}",
            Self::Droplet => "\u{f043}",
            Self::DropletSlash => "\u{f5c7}",
            Self::Drum => "\u{f569}",
            Self::DrumSteelpan => "\u{f56a}",
            Self::DrumstickBite => "\u{f6d7}",
            Self::Dumbbell => "\u{f44b}",
            Self::Dumpster => "\u{f793}",
            Self::DumpsterFire => "\u{f794}",
            Self::Dungeon => "\u{f6d9}",
            Self::E => "\u{45}",
            Self::EarDeaf => "\u{f2a4}",
            Self::EarListen => "\u{f2a2}",
            Self::EarthAfrica => "\u{f57c}",
            Self::EarthAmericas => "\u{f57d}",
            Self::EarthAsia => "\u{f57e}",
            Self::EarthEurope => "\u{f7a2}",
            Self::EarthOceania => "\u{e47b}",
            Self::Egg => "\u{f7fb}",
            Self::Eject => "\u{f052}",
            Self::Elevator => "\u{e16d}",
            Self::Ellipsis => "\u{f141}",
            Self::EllipsisVertical => "\u{f142}",
            Self::Envelope => "\u{f0e0}",
            Self::EnvelopeCircleCheck => "\u{e4e8}",
            Self::EnvelopeOpen => "\u{f2b6}",
            Self::EnvelopeOpenText => "\u{f658}",
            Self::EnvelopesBulk => "\u{f674}",
            Self::Equals => "\u{3d}",
            Self::Eraser => "\u{f12d}",
            Self::Ethernet => "\u{f796}",
            Self::EuroSign => "\u{f153}",
            Self::Exclamation => "\u{21}",
            Self::Expand => "\u{f065}",
            Self::Explosion => "\u{e4e9}",
            Self::Eye => "\u{f06e}",
            Self::EyeDropper => "\u{f1fb}",
            Self::EyeLowVision => "\u{f2a8}",
            Self::EyeSlash => "\u{f070}",
            Self::F => "\u{46}",
            Self::FaceAngry => "\u{f556}",
            Self::FaceDizzy => "\u{f567}",
            Self::FaceFlushed => "\u{f579}",
            Self::FaceFrown => "\u{f119}",
            Self::FaceFrownOpen => "\u{f57a}",
            Self::FaceGrimace => "\u{f57f}",
            Self::FaceGrin => "\u{f580}",
            Self::FaceGrinBeam => "\u{f582}",
            Self::FaceGrinBeamSweat => "\u{f583}",
            Self::FaceGrinHearts => "\u{f584}",
            Self::FaceGrinSquint => "\u{f585}",
            Self::FaceGrinSquintTears => "\u{f586}",
            Self::FaceGrinStars => "\u{f587}",
            Self::FaceGrinTears => "\u{f588}",
            Self::FaceGrinTongue => "\u{f589}",
            Self::FaceGrinTongueSquint => "\u{f58a}",
            Self::FaceGrinTongueWink => "\u{f58b}",
            Self::FaceGrinWide => "\u{f581}",
            Self::FaceGrinWink => "\u{f58c}",
            Self::FaceKiss => "\u{f596}",
            Self::FaceKissBeam => "\u{f597}",
            Self::FaceKissWinkHeart => "\u{f598}",
            Self::FaceLaugh => "\u{f599}",
            Self::FaceLaughBeam => "\u{f59a}",
            Self::FaceLaughSquint => "\u{f59b}",
            Self::FaceLaughWink => "\u{f59c}",
            Self::FaceMeh => "\u{f11a}",
            Self::FaceMehBlank => "\u{f5a4}",
            Self::FaceRollingEyes => "\u{f5a5}",
            Self::FaceSadCry => "\u{f5b3}",
            Self::FaceSadTear => "\u{f5b4}",
            Self::FaceSmile => "\u{f118}",
            Self::FaceSmileBeam => "\u{f5b8}",
            Self::FaceSmileWink => "\u{f4da}",
            Self::FaceSurprise => "\u{f5c2}",
            Self::FaceTired => "\u{f5c8}",
            Self::Fan => "\u{f863}",
            Self::Faucet => "\u{e005}",
            Self::FaucetDrip => "\u{e006}",
            Self::Fax => "\u{f1ac}",
            Self::Feather => "\u{f52d}",
            Self::FeatherPointed => "\u{f56b}",
            Self::Ferry => "\u{e4ea}",
            Self::File => "\u{f15b}",
            Self::FileArrowDown => "\u{f56d}",
            Self::FileArrowUp => "\u{f574}",
            Self::FileAudio => "\u{f1c7}",
            Self::FileCircleCheck => "\u{e5a0}",
            Self::FileCircleExclamation => "\u{e4eb}",
            Self::FileCircleMinus => "\u{e4ed}",
            Self::FileCirclePlus => "\u{e494}",
            Self::FileCircleQuestion => "\u{e4ef}",
            Self::FileCircleXmark => "\u{e5a1}",
            Self::FileCode => "\u{f1c9}",
            Self::FileContract => "\u{f56c}",
            Self::FileCsv => "\u{f6dd}",
            Self::FileExcel => "\u{f1c3}",
            Self::FileExport => "\u{f56e}",
            Self::FileFragment => "\u{e697}",
            Self::FileHalfDashed => "\u{e698}",
            Self::FileImage => "\u{f1c5}",
            Self::FileImport => "\u{f56f}",
            Self::FileInvoice => "\u{f570}",
            Self::FileInvoiceDollar => "\u{f571}",
            Self::FileLines => "\u{f15c}",
            Self::FileMedical => "\u{f477}",
            Self::FilePdf => "\u{f1c1}",
            Self::FilePen => "\u{f31c}",
            Self::FilePowerpoint => "\u{f1c4}",
            Self::FilePrescription => "\u{f572}",
            Self::FileShield => "\u{e4f0}",
            Self::FileSignature => "\u{f573}",
            Self::FileVideo => "\u{f1c8}",
            Self::FileWaveform => "\u{f478}",
            Self::FileWord => "\u{f1c2}",
            Self::FileZipper => "\u{f1c6}",
            Self::Fill => "\u{f575}",
            Self::FillDrip => "\u{f576}",
            Self::Film => "\u{f008}",
            Self::Filter => "\u{f0b0}",
            Self::FilterCircleDollar => "\u{f662}",
            Self::FilterCircleXmark => "\u{e17b}",
            Self::Fingerprint => "\u{f577}",
            Self::Fire => "\u{f06d}",
            Self::FireBurner => "\u{e4f1}",
            Self::FireExtinguisher => "\u{f134}",
            Self::FireFlameCurved => "\u{f7e4}",
            Self::FireFlameSimple => "\u{f46a}",
            Self::Fish => "\u{f578}",
            Self::FishFins => "\u{e4f2}",
            Self::Flag => "\u{f024}",
            Self::FlagCheckered => "\u{f11e}",
            Self::FlagUsa => "\u{f74d}",
            Self::Flask => "\u{f0c3}",
            Self::FlaskVial => "\u{e4f3}",
            Self::FloppyDisk => "\u{f0c7}",
            Self::FlorinSign => "\u{e184}",
            Self::Folder => "\u{f07b}",
            Self::FolderClosed => "\u{e185}",
            Self::FolderMinus => "\u{f65d}",
            Self::FolderOpen => "\u{f07c}",
            Self::FolderPlus => "\u{f65e}",
            Self::FolderTree => "\u{f802}",
            Self::Font => "\u{f031}",
            Self::FontAwesome => "\u{f2b4}",
            Self::Football => "\u{f44e}",
            Self::Forward => "\u{f04e}",
            Self::ForwardFast => "\u{f050}",
            Self::ForwardStep => "\u{f051}",
            Self::FrancSign => "\u{e18f}",
            Self::Frog => "\u{f52e}",
            Self::Futbol => "\u{f1e3}",
            Self::G => "\u{47}",
            Self::Gamepad => "\u{f11b}",
            Self::GasPump => "\u{f52f}",
            Self::Gauge => "\u{f624}",
            Self::GaugeHigh => "\u{f625}",
            Self::GaugeSimple => "\u{f629}",
            Self::GaugeSimpleHigh => "\u{f62a}",
            Self::Gavel => "\u{f0e3}",
            Self::Gear => "\u{f013}",
            Self::Gears => "\u{f085}",
            Self::Gem => "\u{f3a5}",
            Self::Genderless => "\u{f22d}",
            Self::Ghost => "\u{f6e2}",
            Self::Gift => "\u{f06b}",
            Self::Gifts => "\u{f79c}",
            Self::GlassWater => "\u{e4f4}",
            Self::GlassWaterDroplet => "\u{e4f5}",
            Self::Glasses => "\u{f530}",
            Self::Globe => "\u{f0ac}",
            Self::GolfBallTee => "\u{f450}",
            Self::Gopuram => "\u{f664}",
            Self::GraduationCap => "\u{f19d}",
            Self::GreaterThan => "\u{3e}",
            Self::GreaterThanEqual => "\u{f532}",
            Self::Grip => "\u{f58d}",
            Self::GripLines => "\u{f7a4}",
            Self::GripLinesVertical => "\u{f7a5}",
            Self::GripVertical => "\u{f58e}",
            Self::GroupArrowsRotate => "\u{e4f6}",
            Self::GuaraniSign => "\u{e19a}",
            Self::Guitar => "\u{f7a6}",
            Self::Gun => "\u{e19b}",
            Self::H => "\u{48}",
            Self::Hammer => "\u{f6e3}",
            Self::Hamsa => "\u{f665}",
            Self::Hand => "\u{f256}",
            Self::HandBackFist => "\u{f255}",
            Self::HandDots => "\u{f461}",
            Self::HandFist => "\u{f6de}",
            Self::HandHolding => "\u{f4bd}",
            Self::HandHoldingDollar => "\u{f4c0}",
            Self::HandHoldingDroplet => "\u{f4c1}",
            Self::HandHoldingHand => "\u{e4f7}",
            Self::HandHoldingHeart => "\u{f4be}",
            Self::HandHoldingMedical => "\u{e05c}",
            Self::HandLizard => "\u{f258}",
            Self::HandMiddleFinger => "\u{f806}",
            Self::HandPeace => "\u{f25b}",
            Self::HandPointDown => "\u{f0a7}",
            Self::HandPointLeft => "\u{f0a5}",
            Self::HandPointRight => "\u{f0a4}",
            Self::HandPointUp => "\u{f0a6}",
            Self::HandPointer => "\u{f25a}",
            Self::HandScissors => "\u{f257}",
            Self::HandSparkles => "\u{e05d}",
            Self::HandSpock => "\u{f259}",
            Self::Handcuffs => "\u{e4f8}",
            Self::Hands => "\u{f2a7}",
            Self::HandsAslInterpreting => "\u{f2a3}",
            Self::HandsBound => "\u{e4f9}",
            Self::HandsBubbles => "\u{e05e}",
            Self::HandsClapping => "\u{e1a8}",
            Self::HandsHolding => "\u{f4c2}",
            Self::HandsHoldingChild => "\u{e4fa}",
            Self::HandsHoldingCircle => "\u{e4fb}",
            Self::HandsPraying => "\u{f684}",
            Self::Handshake => "\u{f2b5}",
            Self::HandshakeAngle => "\u{f4c4}",
            Self::HandshakeSimple => "\u{f4c6}",
            Self::HandshakeSimpleSlash => "\u{e05f}",
            Self::HandshakeSlash => "\u{e060}",
            Self::Hanukiah => "\u{f6e6}",
            Self::HardDrive => "\u{f0a0}",
            Self::Hashtag => "\u{23}",
            Self::HatCowboy => "\u{f8c0}",
            Self::HatCowboySide => "\u{f8c1}",
            Self::HatWizard => "\u{f6e8}",
            Self::HeadSideCough => "\u{e061}",
            Self::HeadSideCoughSlash => "\u{e062}",
            Self::HeadSideMask => "\u{e063}",
            Self::HeadSideVirus => "\u{e064}",
            Self::Heading => "\u{f1dc}",
            Self::Headphones => "\u{f025}",
            Self::HeadphonesSimple => "\u{f58f}",
            Self::Headset => "\u{f590}",
            Self::Heart => "\u{f004}",
            Self::HeartCircleBolt => "\u{e4fc}",
            Self::HeartCircleCheck => "\u{e4fd}",
            Self::HeartCircleExclamation => "\u{e4fe}",
            Self::HeartCircleMinus => "\u{e4ff}",
            Self::HeartCirclePlus => "\u{e500}",
            Self::HeartCircleXmark => "\u{e501}",
            Self::HeartCrack => "\u{f7a9}",
            Self::HeartPulse => "\u{f21e}",
            Self::Helicopter => "\u{f533}",
            Self::HelicopterSymbol => "\u{e502}",
            Self::HelmetSafety => "\u{f807}",
            Self::HelmetUn => "\u{e503}",
            Self::HexagonNodes => "\u{e699}",
            Self::HexagonNodesBolt => "\u{e69a}",
            Self::Highlighter => "\u{f591}",
            Self::HillAvalanche => "\u{e507}",
            Self::HillRockslide => "\u{e508}",
            Self::Hippo => "\u{f6ed}",
            Self::HockeyPuck => "\u{f453}",
            Self::HollyBerry => "\u{f7aa}",
            Self::Horse => "\u{f6f0}",
            Self::HorseHead => "\u{f7ab}",
            Self::Hospital => "\u{f0f8}",
            Self::HospitalUser => "\u{f80d}",
            Self::HotTubPerson => "\u{f593}",
            Self::Hotdog => "\u{f80f}",
            Self::Hotel => "\u{f594}",
            Self::Hourglass => "\u{f254}",
            Self::HourglassEnd => "\u{f253}",
            Self::HourglassHalf => "\u{f252}",
            Self::HourglassStart => "\u{f251}",
            Self::House => "\u{f015}",
            Self::HouseChimney => "\u{e3af}",
            Self::HouseChimneyCrack => "\u{f6f1}",
            Self::HouseChimneyMedical => "\u{f7f2}",
            Self::HouseChimneyUser => "\u{e065}",
            Self::HouseChimneyWindow => "\u{e00d}",
            Self::HouseCircleCheck => "\u{e509}",
            Self::HouseCircleExclamation => "\u{e50a}",
            Self::HouseCircleXmark => "\u{e50b}",
            Self::HouseCrack => "\u{e3b1}",
            Self::HouseFire => "\u{e50c}",
            Self::HouseFlag => "\u{e50d}",
            Self::HouseFloodWater => "\u{e50e}",
            Self::HouseFloodWaterCircleArrowRight => "\u{e50f}",
            Self::HouseLaptop => "\u{e066}",
            Self::HouseLock => "\u{e510}",
            Self::HouseMedical => "\u{e3b2}",
            Self::HouseMedicalCircleCheck => "\u{e511}",
            Self::HouseMedicalCircleExclamation => "\u{e512}",
            Self::HouseMedicalCircleXmark => "\u{e513}",
            Self::HouseMedicalFlag => "\u{e514}",
            Self::HouseSignal => "\u{e012}",
            Self::HouseTsunami => "\u{e515}",
            Self::HouseUser => "\u{e1b0}",
            Self::HryvniaSign => "\u{f6f2}",
            Self::Hurricane => "\u{f751}",
            Self::I => "\u{49}",
            Self::ICursor => "\u{f246}",
            Self::IceCream => "\u{f810}",
            Self::Icicles => "\u{f7ad}",
            Self::Icons => "\u{f86d}",
            Self::IdBadge => "\u{f2c1}",
            Self::IdCard => "\u{f2c2}",
            Self::IdCardClip => "\u{f47f}",
            Self::Igloo => "\u{f7ae}",
            Self::Image => "\u{f03e}",
            Self::ImagePortrait => "\u{f3e0}",
            Self::Images => "\u{f302}",
            Self::Inbox => "\u{f01c}",
            Self::Indent => "\u{f03c}",
            Self::IndianRupeeSign => "\u{e1bc}",
            Self::Industry => "\u{f275}",
            Self::Infinity => "\u{f534}",
            Self::Info => "\u{f129}",
            Self::Italic => "\u{f033}",
            Self::J => "\u{4a}",
            Self::Jar => "\u{e516}",
            Self::JarWheat => "\u{e517}",
            Self::Jedi => "\u{f669}",
            Self::JetFighter => "\u{f0fb}",
            Self::JetFighterUp => "\u{e518}",
            Self::Joint => "\u{f595}",
            Self::JugDetergent => "\u{e519}",
            Self::K => "\u{4b}",
            Self::Kaaba => "\u{f66b}",
            Self::Key => "\u{f084}",
            Self::Keyboard => "\u{f11c}",
            Self::Khanda => "\u{f66d}",
            Self::KipSign => "\u{e1c4}",
            Self::KitMedical => "\u{f479}",
            Self::KitchenSet => "\u{e51a}",
            Self::KiwiBird => "\u{f535}",
            Self::L => "\u{4c}",
            Self::LandMineOn => "\u{e51b}",
            Self::Landmark => "\u{f66f}",
            Self::LandmarkDome => "\u{f752}",
            Self::LandmarkFlag => "\u{e51c}",
            Self::Language => "\u{f1ab}",
            Self::Laptop => "\u{f109}",
            Self::LaptopCode => "\u{f5fc}",
            Self::LaptopFile => "\u{e51d}",
            Self::LaptopMedical => "\u{f812}",
            Self::LariSign => "\u{e1c8}",
            Self::LayerGroup => "\u{f5fd}",
            Self::Leaf => "\u{f06c}",
            Self::LeftLong => "\u{f30a}",
            Self::LeftRight => "\u{f337}",
            Self::Lemon => "\u{f094}",
            Self::LessThan => "\u{3c}",
            Self::LessThanEqual => "\u{f537}",
            Self::LifeRing => "\u{f1cd}",
            Self::Lightbulb => "\u{f0eb}",
            Self::LinesLeaning => "\u{e51e}",
            Self::Link => "\u{f0c1}",
            Self::LinkSlash => "\u{f127}",
            Self::LiraSign => "\u{f195}",
            Self::List => "\u{f03a}",
            Self::ListCheck => "\u{f0ae}",
            Self::ListOl => "\u{f0cb}",
            Self::ListUl => "\u{f0ca}",
            Self::LitecoinSign => "\u{e1d3}",
            Self::LocationArrow => "\u{f124}",
            Self::LocationCrosshairs => "\u{f601}",
            Self::LocationDot => "\u{f3c5}",
            Self::LocationPin => "\u{f041}",
            Self::LocationPinLock => "\u{e51f}",
            Self::Lock => "\u{f023}",
            Self::LockOpen => "\u{f3c1}",
            Self::Locust => "\u{e520}",
            Self::Lungs => "\u{f604}",
            Self::LungsVirus => "\u{e067}",
            Self::M => "\u{4d}",
            Self::Magnet => "\u{f076}",
            Self::MagnifyingGlass => "\u{f002}",
            Self::MagnifyingGlassArrowRight => "\u{e521}",
            Self::MagnifyingGlassChart => "\u{e522}",
            Self::MagnifyingGlassDollar => "\u{f688}",
            Self::MagnifyingGlassLocation => "\u{f689}",
            Self::MagnifyingGlassMinus => "\u{f010}",
            Self::MagnifyingGlassPlus => "\u{f00e}",
            Self::ManatSign => "\u{e1d5}",
            Self::Map => "\u{f279}",
            Self::MapLocation => "\u{f59f}",
            Self::MapLocationDot => "\u{f5a0}",
            Self::MapPin => "\u{f276}",
            Self::Marker => "\u{f5a1}",
            Self::Mars => "\u{f222}",
            Self::MarsAndVenus => "\u{f224}",
            Self::MarsAndVenusBurst => "\u{e523}",
            Self::MarsDouble => "\u{f227}",
            Self::MarsStroke => "\u{f229}",
            Self::MarsStrokeRight => "\u{f22b}",
            Self::MarsStrokeUp => "\u{f22a}",
            Self::MartiniGlass => "\u{f57b}",
            Self::MartiniGlassCitrus => "\u{f561}",
            Self::MartiniGlassEmpty => "\u{f000}",
            Self::Mask => "\u{f6fa}",
            Self::MaskFace => "\u{e1d7}",
            Self::MaskVentilator => "\u{e524}",
            Self::MasksTheater => "\u{f630}",
            Self::MattressPillow => "\u{e525}",
            Self::Maximize => "\u{f31e}",
            Self::Medal => "\u{f5a2}",
            Self::Memory => "\u{f538}",
            Self::Menorah => "\u{f676}",
            Self::Mercury => "\u{f223}",
            Self::Message => "\u{f27a}",
            Self::Meteor => "\u{f753}",
            Self::Microchip => "\u{f2db}",
            Self::Microphone => "\u{f130}",
            Self::MicrophoneLines => "\u{f3c9}",
            Self::MicrophoneLinesSlash => "\u{f539}",
            Self::MicrophoneSlash => "\u{f131}",
            Self::Microscope => "\u{f610}",
            Self::MillSign => "\u{e1ed}",
            Self::Minimize => "\u{f78c}",
            Self::Minus => "\u{f068}",
            Self::Mitten => "\u{f7b5}",
            Self::Mobile => "\u{f3ce}",
            Self::MobileButton => "\u{f10b}",
            Self::MobileRetro => "\u{e527}",
            Self::MobileScreen => "\u{f3cf}",
            Self::MobileScreenButton => "\u{f3cd}",
            Self::MoneyBill => "\u{f0d6}",
            Self::MoneyBill1 => "\u{f3d1}",
            Self::MoneyBill1Wave => "\u{f53b}",
            Self::MoneyBillTransfer => "\u{e528}",
            Self::MoneyBillTrendUp => "\u{e529}",
            Self::MoneyBillWave => "\u{f53a}",
            Self::MoneyBillWheat => "\u{e52a}",
            Self::MoneyBills => "\u{e1f3}",
            Self::MoneyCheck => "\u{f53c}",
            Self::MoneyCheckDollar => "\u{f53d}",
            Self::Monument => "\u{f5a6}",
            Self::Moon => "\u{f186}",
            Self::MortarPestle => "\u{f5a7}",
            Self::Mosque => "\u{f678}",
            Self::Mosquito => "\u{e52b}",
            Self::MosquitoNet => "\u{e52c}",
            Self::Motorcycle => "\u{f21c}",
            Self::Mound => "\u{e52d}",
            Self::Mountain => "\u{f6fc}",
            Self::MountainCity => "\u{e52e}",
            Self::MountainSun => "\u{e52f}",
            Self::MugHot => "\u{f7b6}",
            Self::MugSaucer => "\u{f0f4}",
            Self::Music => "\u{f001}",
            Self::N => "\u{4e}",
            Self::NairaSign => "\u{e1f6}",
            Self::NetworkWired => "\u{f6ff}",
            Self::Neuter => "\u{f22c}",
            Self::Newspaper => "\u{f1ea}",
            Self::NotEqual => "\u{f53e}",
            Self::Notdef => "\u{e1fe}",
            Self::NoteSticky => "\u{f249}",
            Self::NotesMedical => "\u{f481}",
            Self::O => "\u{4f}",
            Self::ObjectGroup => "\u{f247}",
            Self::ObjectUngroup => "\u{f248}",
            Self::OilCan => "\u{f613}",
            Self::OilWell => "\u{e532}",
            Self::Om => "\u{f679}",
            Self::Otter => "\u{f700}",
            Self::Outdent => "\u{f03b}",
            Self::P => "\u{50}",
            Self::Pager => "\u{f815}",
            Self::PaintRoller => "\u{f5aa}",
            Self::Paintbrush => "\u{f1fc}",
            Self::Palette => "\u{f53f}",
            Self::Pallet => "\u{f482}",
            Self::Panorama => "\u{e209}",
            Self::PaperPlane => "\u{f1d8}",
            Self::Paperclip => "\u{f0c6}",
            Self::ParachuteBox => "\u{f4cd}",
            Self::Paragraph => "\u{f1dd}",
            Self::Passport => "\u{f5ab}",
            Self::Paste => "\u{f0ea}",
            Self::Pause => "\u{f04c}",
            Self::Paw => "\u{f1b0}",
            Self::Peace => "\u{f67c}",
            Self::Pen => "\u{f304}",
            Self::PenClip => "\u{f305}",
            Self::PenFancy => "\u{f5ac}",
            Self::PenNib => "\u{f5ad}",
            Self::PenRuler => "\u{f5ae}",
            Self::PenToSquare => "\u{f044}",
            Self::Pencil => "\u{f303}",
            Self::PeopleArrows => "\u{e068}",
            Self::PeopleCarryBox => "\u{f4ce}",
            Self::PeopleGroup => "\u{e533}",
            Self::PeopleLine => "\u{e534}",
            Self::PeoplePulling => "\u{e535}",
            Self::PeopleRobbery => "\u{e536}",
            Self::PeopleRoof => "\u{e537}",
            Self::PepperHot => "\u{f816}",
            Self::Percent => "\u{25}",
            Self::Person => "\u{f183}",
            Self::PersonArrowDownToLine => "\u{e538}",
            Self::PersonArrowUpFromLine => "\u{e539}",
            Self::PersonBiking => "\u{f84a}",
            Self::PersonBooth => "\u{f756}",
            Self::PersonBreastfeeding => "\u{e53a}",
            Self::PersonBurst => "\u{e53b}",
            Self::PersonCane => "\u{e53c}",
            Self::PersonChalkboard => "\u{e53d}",
            Self::PersonCircleCheck => "\u{e53e}",
            Self::PersonCircleExclamation => "\u{e53f}",
            Self::PersonCircleMinus => "\u{e540}",
            Self::PersonCirclePlus => "\u{e541}",
            Self::PersonCircleQuestion => "\u{e542}",
            Self::PersonCircleXmark => "\u{e543}",
            Self::PersonDigging => "\u{f85e}",
            Self::PersonDotsFromLine => "\u{f470}",
            Self::PersonDress => "\u{f182}",
            Self::PersonDressBurst => "\u{e544}",
            Self::PersonDrowning => "\u{e545}",
            Self::PersonFalling => "\u{e546}",
            Self::PersonFallingBurst => "\u{e547}",
            Self::PersonHalfDress => "\u{e548}",
            Self::PersonHarassing => "\u{e549}",
            Self::PersonHiking => "\u{f6ec}",
            Self::PersonMilitaryPointing => "\u{e54a}",
            Self::PersonMilitaryRifle => "\u{e54b}",
            Self::PersonMilitaryToPerson => "\u{e54c}",
            Self::PersonPraying => "\u{f683}",
            Self::PersonPregnant => "\u{e31e}",
            Self::PersonRays => "\u{e54d}",
            Self::PersonRifle => "\u{e54e}",
            Self::PersonRunning => "\u{f70c}",
            Self::PersonShelter => "\u{e54f}",
            Self::PersonSkating => "\u{f7c5}",
            Self::PersonSkiing => "\u{f7c9}",
            Self::PersonSkiingNordic => "\u{f7ca}",
            Self::PersonSnowboarding => "\u{f7ce}",
            Self::PersonSwimming => "\u{f5c4}",
            Self::PersonThroughWindow => "\u{e5a9}",
            Self::PersonWalking => "\u{f554}",
            Self::PersonWalkingArrowLoopLeft => "\u{e551}",
            Self::PersonWalkingArrowRight => "\u{e552}",
            Self::PersonWalkingDashedLineArrowRight => "\u{e553}",
            Self::PersonWalkingLuggage => "\u{e554}",
            Self::PersonWalkingWithCane => "\u{f29d}",
            Self::PesetaSign => "\u{e221}",
            Self::PesoSign => "\u{e222}",
            Self::Phone => "\u{f095}",
            Self::PhoneFlip => "\u{f879}",
            Self::PhoneSlash => "\u{f3dd}",
            Self::PhoneVolume => "\u{f2a0}",
            Self::PhotoFilm => "\u{f87c}",
            Self::PiggyBank => "\u{f4d3}",
            Self::Pills => "\u{f484}",
            Self::PizzaSlice => "\u{f818}",
            Self::PlaceOfWorship => "\u{f67f}",
            Self::Plane => "\u{f072}",
            Self::PlaneArrival => "\u{f5af}",
            Self::PlaneCircleCheck => "\u{e555}",
            Self::PlaneCircleExclamation => "\u{e556}",
            Self::PlaneCircleXmark => "\u{e557}",
            Self::PlaneDeparture => "\u{f5b0}",
            Self::PlaneLock => "\u{e558}",
            Self::PlaneSlash => "\u{e069}",
            Self::PlaneUp => "\u{e22d}",
            Self::PlantWilt => "\u{e5aa}",
            Self::PlateWheat => "\u{e55a}",
            Self::Play => "\u{f04b}",
            Self::Plug => "\u{f1e6}",
            Self::PlugCircleBolt => "\u{e55b}",
            Self::PlugCircleCheck => "\u{e55c}",
            Self::PlugCircleExclamation => "\u{e55d}",
            Self::PlugCircleMinus => "\u{e55e}",
            Self::PlugCirclePlus => "\u{e55f}",
            Self::PlugCircleXmark => "\u{e560}",
            Self::Plus => "\u{2b}",
            Self::PlusMinus => "\u{e43c}",
            Self::Podcast => "\u{f2ce}",
            Self::Poo => "\u{f2fe}",
            Self::PooStorm => "\u{f75a}",
            Self::Poop => "\u{f619}",
            Self::PowerOff => "\u{f011}",
            Self::Prescription => "\u{f5b1}",
            Self::PrescriptionBottle => "\u{f485}",
            Self::PrescriptionBottleMedical => "\u{f486}",
            Self::Print => "\u{f02f}",
            Self::PumpMedical => "\u{e06a}",
            Self::PumpSoap => "\u{e06b}",
            Self::PuzzlePiece => "\u{f12e}",
            Self::Q => "\u{51}",
            Self::Qrcode => "\u{f029}",
            Self::Question => "\u{3f}",
            Self::QuoteLeft => "\u{f10d}",
            Self::QuoteRight => "\u{f10e}",
            Self::R => "\u{52}",
            Self::Radiation => "\u{f7b9}",
            Self::Radio => "\u{f8d7}",
            Self::Rainbow => "\u{f75b}",
            Self::RankingStar => "\u{e561}",
            Self::Receipt => "\u{f543}",
            Self::RecordVinyl => "\u{f8d9}",
            Self::RectangleAd => "\u{f641}",
            Self::RectangleList => "\u{f022}",
            Self::RectangleXmark => "\u{f410}",
            Self::Recycle => "\u{f1b8}",
            Self::Registered => "\u{f25d}",
            Self::Repeat => "\u{f363}",
            Self::Reply => "\u{f3e5}",
            Self::ReplyAll => "\u{f122}",
            Self::Republican => "\u{f75e}",
            Self::Restroom => "\u{f7bd}",
            Self::Retweet => "\u{f079}",
            Self::Ribbon => "\u{f4d6}",
            Self::RightFromBracket => "\u{f2f5}",
            Self::RightLeft => "\u{f362}",
            Self::RightLong => "\u{f30b}",
            Self::RightToBracket => "\u{f2f6}",
            Self::Ring => "\u{f70b}",
            Self::Road => "\u{f018}",
            Self::RoadBarrier => "\u{e562}",
            Self::RoadBridge => "\u{e563}",
            Self::RoadCircleCheck => "\u{e564}",
            Self::RoadCircleExclamation => "\u{e565}",
            Self::RoadCircleXmark => "\u{e566}",
            Self::RoadLock => "\u{e567}",
            Self::RoadSpikes => "\u{e568}",
            Self::Robot => "\u{f544}",
            Self::Rocket => "\u{f135}",
            Self::Rotate => "\u{f2f1}",
            Self::RotateLeft => "\u{f2ea}",
            Self::RotateRight => "\u{f2f9}",
            Self::Route => "\u{f4d7}",
            Self::Rss => "\u{f09e}",
            Self::RubleSign => "\u{f158}",
            Self::Rug => "\u{e569}",
            Self::Ruler => "\u{f545}",
            Self::RulerCombined => "\u{f546}",
            Self::RulerHorizontal => "\u{f547}",
            Self::RulerVertical => "\u{f548}",
            Self::RupeeSign => "\u{f156}",
            Self::RupiahSign => "\u{e23d}",
            Self::S => "\u{53}",
            Self::SackDollar => "\u{f81d}",
            Self::SackXmark => "\u{e56a}",
            Self::Sailboat => "\u{e445}",
            Self::Satellite => "\u{f7bf}",
            Self::SatelliteDish => "\u{f7c0}",
            Self::ScaleBalanced => "\u{f24e}",
            Self::ScaleUnbalanced => "\u{f515}",
            Self::ScaleUnbalancedFlip => "\u{f516}",
            Self::School => "\u{f549}",
            Self::SchoolCircleCheck => "\u{e56b}",
            Self::SchoolCircleExclamation => "\u{e56c}",
            Self::SchoolCircleXmark => "\u{e56d}",
            Self::SchoolFlag => "\u{e56e}",
            Self::SchoolLock => "\u{e56f}",
            Self::Scissors => "\u{f0c4}",
            Self::Screwdriver => "\u{f54a}",
            Self::ScrewdriverWrench => "\u{f7d9}",
            Self::Scroll => "\u{f70e}",
            Self::ScrollTorah => "\u{f6a0}",
            Self::SdCard => "\u{f7c2}",
            Self::Section => "\u{e447}",
            Self::Seedling => "\u{f4d8}",
            Self::Server => "\u{f233}",
            Self::Shapes => "\u{f61f}",
            Self::Share => "\u{f064}",
            Self::ShareFromSquare => "\u{f14d}",
            Self::ShareNodes => "\u{f1e0}",
            Self::SheetPlastic => "\u{e571}",
            Self::ShekelSign => "\u{f20b}",
            Self::Shield => "\u{f132}",
            Self::ShieldCat => "\u{e572}",
            Self::ShieldDog => "\u{e573}",
            Self::ShieldHalved => "\u{f3ed}",
            Self::ShieldHeart => "\u{e574}",
            Self::ShieldVirus => "\u{e06c}",
            Self::Ship => "\u{f21a}",
            Self::Shirt => "\u{f553}",
            Self::ShoePrints => "\u{f54b}",
            Self::Shop => "\u{f54f}",
            Self::ShopLock => "\u{e4a5}",
            Self::ShopSlash => "\u{e070}",
            Self::Shower => "\u{f2cc}",
            Self::Shrimp => "\u{e448}",
            Self::Shuffle => "\u{f074}",
            Self::ShuttleSpace => "\u{f197}",
            Self::SignHanging => "\u{f4d9}",
            Self::Signal => "\u{f012}",
            Self::Signature => "\u{f5b7}",
            Self::SignsPost => "\u{f277}",
            Self::SimCard => "\u{f7c4}",
            Self::Sink => "\u{e06d}",
            Self::Sitemap => "\u{f0e8}",
            Self::Skull => "\u{f54c}",
            Self::SkullCrossbones => "\u{f714}",
            Self::Slash => "\u{f715}",
            Self::Sleigh => "\u{f7cc}",
            Self::Sliders => "\u{f1de}",
            Self::Smog => "\u{f75f}",
            Self::Smoking => "\u{f48d}",
            Self::Snowflake => "\u{f2dc}",
            Self::Snowman => "\u{f7d0}",
            Self::Snowplow => "\u{f7d2}",
            Self::Soap => "\u{e06e}",
            Self::Socks => "\u{f696}",
            Self::SolarPanel => "\u{f5ba}",
            Self::Sort => "\u{f0dc}",
            Self::SortDown => "\u{f0dd}",
            Self::SortUp => "\u{f0de}",
            Self::Spa => "\u{f5bb}",
            Self::SpaghettiMonsterFlying => "\u{f67b}",
            Self::SpellCheck => "\u{f891}",
            Self::Spider => "\u{f717}",
            Self::Spinner => "\u{f110}",
            Self::Splotch => "\u{f5bc}",
            Self::Spoon => "\u{f2e5}",
            Self::SprayCan => "\u{f5bd}",
            Self::SprayCanSparkles => "\u{f5d0}",
            Self::Square => "\u{f0c8}",
            Self::SquareArrowUpRight => "\u{f14c}",
            Self::SquareBinary => "\u{e69b}",
            Self::SquareCaretDown => "\u{f150}",
            Self::SquareCaretLeft => "\u{f191}",
            Self::SquareCaretRight => "\u{f152}",
            Self::SquareCaretUp => "\u{f151}",
            Self::SquareCheck => "\u{f14a}",
            Self::SquareEnvelope => "\u{f199}",
            Self::SquareFull => "\u{f45c}",
            Self::SquareH => "\u{f0fd}",
            Self::SquareMinus => "\u{f146}",
            Self::SquareNfi => "\u{e576}",
            Self::SquareParking => "\u{f540}",
            Self::SquarePen => "\u{f14b}",
            Self::SquarePersonConfined => "\u{e577}",
            Self::SquarePhone => "\u{f098}",
            Self::SquarePhoneFlip => "\u{f87b}",
            Self::SquarePlus => "\u{f0fe}",
            Self::SquarePollHorizontal => "\u{f682}",
            Self::SquarePollVertical => "\u{f681}",
            Self::SquareRootVariable => "\u{f698}",
            Self::SquareRss => "\u{f143}",
            Self::SquareShareNodes => "\u{f1e1}",
            Self::SquareUpRight => "\u{f360}",
            Self::SquareVirus => "\u{e578}",
            Self::SquareXmark => "\u{f2d3}",
            Self::StaffSnake => "\u{e579}",
            Self::Stairs => "\u{e289}",
            Self::Stamp => "\u{f5bf}",
            Self::Stapler => "\u{e5af}",
            Self::Star => "\u{f005}",
            Self::StarAndCrescent => "\u{f699}",
            Self::StarHalf => "\u{f089}",
            Self::StarHalfStroke => "\u{f5c0}",
            Self::StarOfDavid => "\u{f69a}",
            Self::StarOfLife => "\u{f621}",
            Self::SterlingSign => "\u{f154}",
            Self::Stethoscope => "\u{f0f1}",
            Self::Stop => "\u{f04d}",
            Self::Stopwatch => "\u{f2f2}",
            Self::Stopwatch20 => "\u{e06f}",
            Self::Store => "\u{f54e}",
            Self::StoreSlash => "\u{e071}",
            Self::StreetView => "\u{f21d}",
            Self::Strikethrough => "\u{f0cc}",
            Self::Stroopwafel => "\u{f551}",
            Self::Subscript => "\u{f12c}",
            Self::Suitcase => "\u{f0f2}",
            Self::SuitcaseMedical => "\u{f0fa}",
            Self::SuitcaseRolling => "\u{f5c1}",
            Self::Sun => "\u{f185}",
            Self::SunPlantWilt => "\u{e57a}",
            Self::Superscript => "\u{f12b}",
            Self::Swatchbook => "\u{f5c3}",
            Self::Synagogue => "\u{f69b}",
            Self::Syringe => "\u{f48e}",
            Self::T => "\u{54}",
            Self::Table => "\u{f0ce}",
            Self::TableCells => "\u{f00a}",
            Self::TableCellsColumnLock => "\u{e678}",
            Self::TableCellsLarge => "\u{f009}",
            Self::TableCellsRowLock => "\u{e67a}",
            Self::TableCellsRowUnlock => "\u{e691}",
            Self::TableColumns => "\u{f0db}",
            Self::TableList => "\u{f00b}",
            Self::TableTennisPaddleBall => "\u{f45d}",
            Self::Tablet => "\u{f3fb}",
            Self::TabletButton => "\u{f10a}",
            Self::TabletScreenButton => "\u{f3fa}",
            Self::Tablets => "\u{f490}",
            Self::TachographDigital => "\u{f566}",
            Self::Tag => "\u{f02b}",
            Self::Tags => "\u{f02c}",
            Self::Tape => "\u{f4db}",
            Self::Tarp => "\u{e57b}",
            Self::TarpDroplet => "\u{e57c}",
            Self::Taxi => "\u{f1ba}",
            Self::Teeth => "\u{f62e}",
            Self::TeethOpen => "\u{f62f}",
            Self::TemperatureArrowDown => "\u{e03f}",
            Self::TemperatureArrowUp => "\u{e040}",
            Self::TemperatureEmpty => "\u{f2cb}",
            Self::TemperatureFull => "\u{f2c7}",
            Self::TemperatureHalf => "\u{f2c9}",
            Self::TemperatureHigh => "\u{f769}",
            Self::TemperatureLow => "\u{f76b}",
            Self::TemperatureQuarter => "\u{f2ca}",
            Self::TemperatureThreeQuarters => "\u{f2c8}",
            Self::TengeSign => "\u{f7d7}",
            Self::Tent => "\u{e57d}",
            Self::TentArrowDownToLine => "\u{e57e}",
            Self::TentArrowLeftRight => "\u{e57f}",
            Self::TentArrowTurnLeft => "\u{e580}",
            Self::TentArrowsDown => "\u{e581}",
            Self::Tents => "\u{e582}",
            Self::Terminal => "\u{f120}",
            Self::TextHeight => "\u{f034}",
            Self::TextSlash => "\u{f87d}",
            Self::TextWidth => "\u{f035}",
            Self::Thermometer => "\u{f491}",
            Self::ThumbsDown => "\u{f165}",
            Self::ThumbsUp => "\u{f164}",
            Self::Thumbtack => "\u{f08d}",
            Self::ThumbtackSlash => "\u{e68f}",
            Self::Ticket => "\u{f145}",
            Self::TicketSimple => "\u{f3ff}",
            Self::Timeline => "\u{e29c}",
            Self::ToggleOff => "\u{f204}",
            Self::ToggleOn => "\u{f205}",
            Self::Toilet => "\u{f7d8}",
            Self::ToiletPaper => "\u{f71e}",
            Self::ToiletPaperSlash => "\u{e072}",
            Self::ToiletPortable => "\u{e583}",
            Self::ToiletsPortable => "\u{e584}",
            Self::Toolbox => "\u{f552}",
            Self::Tooth => "\u{f5c9}",
            Self::ToriiGate => "\u{f6a1}",
            Self::Tornado => "\u{f76f}",
            Self::TowerBroadcast => "\u{f519}",
            Self::TowerCell => "\u{e585}",
            Self::TowerObservation => "\u{e586}",
            Self::Tractor => "\u{f722}",
            Self::Trademark => "\u{f25c}",
            Self::TrafficLight => "\u{f637}",
            Self::Trailer => "\u{e041}",
            Self::Train => "\u{f238}",
            Self::TrainSubway => "\u{f239}",
            Self::TrainTram => "\u{e5b4}",
            Self::Transgender => "\u{f225}",
            Self::Trash => "\u{f1f8}",
            Self::TrashArrowUp => "\u{f829}",
            Self::TrashCan => "\u{f2ed}",
            Self::TrashCanArrowUp => "\u{f82a}",
            Self::Tree => "\u{f1bb}",
            Self::TreeCity => "\u{e587}",
            Self::TriangleExclamation => "\u{f071}",
            Self::Trophy => "\u{f091}",
            Self::Trowel => "\u{e589}",
            Self::TrowelBricks => "\u{e58a}",
            Self::Truck => "\u{f0d1}",
            Self::TruckArrowRight => "\u{e58b}",
            Self::TruckDroplet => "\u{e58c}",
            Self::TruckFast => "\u{f48b}",
            Self::TruckField => "\u{e58d}",
            Self::TruckFieldUn => "\u{e58e}",
            Self::TruckFront => "\u{e2b7}",
            Self::TruckMedical => "\u{f0f9}",
            Self::TruckMonster => "\u{f63b}",
            Self::TruckMoving => "\u{f4df}",
            Self::TruckPickup => "\u{f63c}",
            Self::TruckPlane => "\u{e58f}",
            Self::TruckRampBox => "\u{f4de}",
            Self::Tty => "\u{f1e4}",
            Self::TurkishLiraSign => "\u{e2bb}",
            Self::TurnDown => "\u{f3be}",
            Self::TurnUp => "\u{f3bf}",
            Self::Tv => "\u{f26c}",
            Self::U => "\u{55}",
            Self::Umbrella => "\u{f0e9}",
            Self::UmbrellaBeach => "\u{f5ca}",
            Self::Underline => "\u{f0cd}",
            Self::UniversalAccess => "\u{f29a}",
            Self::Unlock => "\u{f09c}",
            Self::UnlockKeyhole => "\u{f13e}",
            Self::UpDown => "\u{f338}",
            Self::UpDownLeftRight => "\u{f0b2}",
            Self::UpLong => "\u{f30c}",
            Self::UpRightAndDownLeftFromCenter => "\u{f424}",
            Self::UpRightFromSquare => "\u{f35d}",
            Self::Upload => "\u{f093}",
            Self::User => "\u{f007}",
            Self::UserAstronaut => "\u{f4fb}",
            Self::UserCheck => "\u{f4fc}",
            Self::UserClock => "\u{f4fd}",
            Self::UserDoctor => "\u{f0f0}",
            Self::UserGear => "\u{f4fe}",
            Self::UserGraduate => "\u{f501}",
            Self::UserGroup => "\u{f500}",
            Self::UserInjured => "\u{f728}",
            Self::UserLarge => "\u{f406}",
            Self::UserLargeSlash => "\u{f4fa}",
            Self::UserLock => "\u{f502}",
            Self::UserMinus => "\u{f503}",
            Self::UserNinja => "\u{f504}",
            Self::UserNurse => "\u{f82f}",
            Self::UserPen => "\u{f4ff}",
            Self::UserPlus => "\u{f234}",
            Self::UserSecret => "\u{f21b}",
            Self::UserShield => "\u{f505}",
            Self::UserSlash => "\u{f506}",
            Self::UserTag => "\u{f507}",
            Self::UserTie => "\u{f508}",
            Self::UserXmark => "\u{f235}",
            Self::Users => "\u{f0c0}",
            Self::UsersBetweenLines => "\u{e591}",
            Self::UsersGear => "\u{f509}",
            Self::UsersLine => "\u{e592}",
            Self::UsersRays => "\u{e593}",
            Self::UsersRectangle => "\u{e594}",
            Self::UsersSlash => "\u{e073}",
            Self::UsersViewfinder => "\u{e595}",
            Self::Utensils => "\u{f2e7}",
            Self::V => "\u{56}",
            Self::VanShuttle => "\u{f5b6}",
            Self::Vault => "\u{e2c5}",
            Self::VectorSquare => "\u{f5cb}",
            Self::Venus => "\u{f221}",
            Self::VenusDouble => "\u{f226}",
            Self::VenusMars => "\u{f228}",
            Self::Vest => "\u{e085}",
            Self::VestPatches => "\u{e086}",
            Self::Vial => "\u{f492}",
            Self::VialCircleCheck => "\u{e596}",
            Self::VialVirus => "\u{e597}",
            Self::Vials => "\u{f493}",
            Self::Video => "\u{f03d}",
            Self::VideoSlash => "\u{f4e2}",
            Self::Vihara => "\u{f6a7}",
            Self::Virus => "\u{e074}",
            Self::VirusCovid => "\u{e4a8}",
            Self::VirusCovidSlash => "\u{e4a9}",
            Self::VirusSlash => "\u{e075}",
            Self::Viruses => "\u{e076}",
            Self::Voicemail => "\u{f897}",
            Self::Volcano => "\u{f770}",
            Self::Volleyball => "\u{f45f}",
            Self::VolumeHigh => "\u{f028}",
            Self::VolumeLow => "\u{f027}",
            Self::VolumeOff => "\u{f026}",
            Self::VolumeXmark => "\u{f6a9}",
            Self::VrCardboard => "\u{f729}",
            Self::W => "\u{57}",
            Self::WalkieTalkie => "\u{f8ef}",
            Self::Wallet => "\u{f555}",
            Self::WandMagic => "\u{f0d0}",
            Self::WandMagicSparkles => "\u{e2ca}",
            Self::WandSparkles => "\u{f72b}",
            Self::Warehouse => "\u{f494}",
            Self::Water => "\u{f773}",
            Self::WaterLadder => "\u{f5c5}",
            Self::WaveSquare => "\u{f83e}",
            Self::WebAwesome => "\u{e682}",
            Self::WeightHanging => "\u{f5cd}",
            Self::WeightScale => "\u{f496}",
            Self::WheatAwn => "\u{e2cd}",
            Self::WheatAwnCircleExclamation => "\u{e598}",
            Self::Wheelchair => "\u{f193}",
            Self::WheelchairMove => "\u{e2ce}",
            Self::WhiskeyGlass => "\u{f7a0}",
            Self::Wifi => "\u{f1eb}",
            Self::Wind => "\u{f72e}",
            Self::WindowMaximize => "\u{f2d0}",
            Self::WindowMinimize => "\u{f2d1}",
            Self::WindowRestore => "\u{f2d2}",
            Self::WineBottle => "\u{f72f}",
            Self::WineGlass => "\u{f4e3}",
            Self::WineGlassEmpty => "\u{f5ce}",
            Self::WonSign => "\u{f159}",
            Self::Worm => "\u{e599}",
            Self::Wrench => "\u{f0ad}",
            Self::X => "\u{58}",
            Self::XRay => "\u{f497}",
            Self::Xmark => "\u{f00d}",
            Self::XmarksLines => "\u{e59a}",
            Self::Y => "\u{59}",
            Self::YenSign => "\u{f157}",
            Self::YinYang => "\u{f6ad}",
            Self::Z => "\u{5a}",
        }
    }
}

pub fn solid<'a>(c: FontAwesomeSolid) -> Text<'a> {
    text(c.to_string().to_owned()).font(FONT)
}

const FONT: Font = Font {
    family: Family::Name("Font Awesome 6 Free"),
    weight: iced::font::Weight::Black,
    ..Font::DEFAULT
};
